
using Google.Protobuf;
using Cspb;
using Msg;
using System;
using System.Collections.Generic;

namespace Proto
{
   public class ProtoDic
   {
       private static List<uint> _protoId = new List<uint>
       {
            886593042,
            886885047,
            2710377623,
            2125651979,
            106677606,
            106969611,
            1178392331,
            877435033,
            1667207662,
            1597664336,
            3607587249,
            3607879254,
            2073228379,
            2288032317,
            2288324322,
            549788918,
            550014233,
            550080923,
            3174995466,
            3689849500,
            3690141505,
            2093934434,
            4210049195,
            2983359718,
            2983651723,
            2171585808,
            2171877813,
            3555713447,
            951042277,
            4087935962,
            295056376,
            295348381,
            2344249429,
            2344541434,
            2095320942,
            588519556,
            588811561,
            2095612947,
            216792128,
            45339267,
            2160282422,
            2160574427,
            3686526375,
            1393432232,
            785340400,
            785407090,
            758089069,
            164104276,
            4182678041,
            4182970046,
            2537588753,
            1785437646,
            173230967,
            121935706,
            1120511217,
            1120803222,
            4167657068,
            4167949073,
            2880637127,
            4255041178,
            4232976456,
            4233268461,
            4459234,
            3455826683,
            3456118688,
            56457226,
            2977032040,
            3594557289,
            3004757981,
            632078851,
            632370856,
            1369360669,
            1082824085,
            1083116090,
            676277639,
            676569644,
            1252109149,
            647510593,
            3458612134,
            3506819525,
            2506717741,
            3375369011,
            3375661016,
            3458904139,
            4100711083,
            4101003088,
            3826852552,
            3827144557,
            3646383917,
            3646675922,
            4269635191,
            3401444076,
            3401736081,
            1878071574,
            1762188444,
            3528409318,
            645357453,
            710657457,
            710949462,
            2265847943,
            2266139948,
            236235688,
            236527693,
            35986352,
            1812994133,
            1813286138,
            129052351,
            424616085,
            424908090,
            129344356,
            3467346729,
            3467638734,
            1051697520,
            1051989525,
            1978225553,
            1978517558,
            2364359968,
            2364651973,
            1298765115,
            1299057120,
            2784124526,
            2784416531,
            1652302216,
            3072748649,
            3511318755,
            2721616563,
            2721908568,
            2025315165,
            3975795667,
            3976087672,
            1125667736,
            513174743,
            1240771857,
            1241063862,
            968546124,
            968838129,
            3159291991,
            3159583996,
            1865153222,
            1865445227,
            785746337,
            786038342,
            2600503131,
            2600795136,
            2999959516,
            3000251521,
            943917744,
            944209749,
            2347674411,
            809024113,
            120854016,
            809316118,
            2073002016,
            2073294021,
            2910866523,
            1118565993,
            141040449,
            141332454,
            783817628,
            4113331167,
            160861990,
            160928680,
            3722562964,
            3722854969,
            3284079804,
            3284371809,
            3889906176,
            3890198181,
            1070549456,
            103298714,
            232621568,
            444212367,
            444504372,
            1646162620,
            2738059605,
            1750487903,
            4024826564,
            2581114299,
            1305311240,
            1305603245,
            973056614,
            3903314428,
            3903606433,
            973348619,
            3028410300,
            3828427248,
            3828719253,
            2033838701,
            2034130706,
            670239602,
            670464917,
            670531607,
            1411264265,
            3108157962,
            3108449967,
            3997760971,
            3998052976,
            332974955,
            333200270,
            3889645223,
            3360666333,
            3360733023,
            1198011188,
            1198303193,
            3804459804,
            3804751809,
            133362805,
            2604838009,
            382278005,
            382570010,
            4250125462,
            4250417467,
            4239569506,
            4239861511,
            858891554,
            3763795911,
            3764087916,
            122016988,
            122308993,
            2100280149,
            2100572154,
            1987719555,
            1988011560,
            2576035970,
            157847089,
            158139094,
            2408789584,
            2409081589,
            65718581,
            220896338,
            2631854496,
            2632146501,
            663930187,
            664222192,
            2450476125,
            2450768130,
            4187509635,
            4187734950,
            4187801640,
            1660720207,
            1661012212,
            1039090410,
            201001902,
            38903085,
            201293907,
            1011373350,
            1011665355,
            900134523,
            900426528,
            3596085430,
            3571639929,
            3626677676,
            196090434,
            196382439,
            3094939550,
            3884695904,
            3884987909,
            1499063199,
            1499355204,
            3519688928,
            3024418002,
            3574365467,
            927775002,
            3974909302,
            3975201307,
            121024122,
            1044635541,
            1044702231,
            1325261889,
            4133867637,
            4134159642,
            1658533687,
            2577171758,
            3351280735,
            2585485501,
            2585777506,
            1590807178,
            2140309531,
            2140601536,
            2561232351,
            2561524356,
            2461239273,
            2461531278,
            842405505,
            2064248156,
            2064540161,
            2052956035,
            2053248040,
            2315640770,
            504281929,
            168364795,
            3370926058,
            1928102495,
            1928394500,
            2634915076,
            1446556802,
            1446848807,
            338594153,
            338886158,
            2072600613,
            2072892618,
            489282124,
            489574129,
            1249648644,
            2597107804,
            4067998605,
            3672476169,
        };

      private static List<Type>_protoType = new List<Type>
      {
            typeof(AccountLinkAck),
            typeof(AccountLinkReq),
            typeof(AddUnionMarkReq),
            typeof(AffairNtf),
            typeof(AllotAsgnAck),
            typeof(AllotAsgnReq),
            typeof(ApplyUnionByNameReq),
            typeof(ApplyUnionReq),
            typeof(AppointUnionMemberTitleReq),
            typeof(ApproveApplyUnionReq),
            typeof(AuthAck),
            typeof(AuthReq),
            typeof(AwardNtf),
            typeof(BReportBasicAck),
            typeof(BReportBasicReq),
            typeof(BReportDetailAck),
            typeof(BReportDetailNtf),
            typeof(BReportDetailReq),
            typeof(BReportNtf),
            typeof(BReportsAck),
            typeof(BReportsReq),
            typeof(BasicNtf),
            typeof(BattleAwardNtf),
            typeof(BindPassportAck),
            typeof(BindPassportReq),
            typeof(BuildCityAck),
            typeof(BuildCityReq),
            typeof(CancelApplyUnionReq),
            typeof(CancelDemiseReq),
            typeof(CancelUpgradeBuildReq),
            typeof(ChangeAvatarAck),
            typeof(ChangeAvatarReq),
            typeof(ChangeIntroAck),
            typeof(ChangeIntroReq),
            typeof(ChangeNameAck),
            typeof(ChangeNameCheckAck),
            typeof(ChangeNameCheckReq),
            typeof(ChangeNameReq),
            typeof(CharCreateReq),
            typeof(CharLoginReq),
            typeof(CharacterCreateCheckAck),
            typeof(CharacterCreateCheckReq),
            typeof(ChatAccountNtf),
            typeof(ChatListReq),
            typeof(ChatNtf),
            typeof(ChatReq),
            typeof(ChatRoomNtf),
            typeof(CityInvincibleReq),
            typeof(CollectBReportAck),
            typeof(CollectBReportReq),
            typeof(CollectLandReq),
            typeof(CollectLandsNtf),
            typeof(CollectTaxesReq),
            typeof(CommonAck),
            typeof(ConflictListAck),
            typeof(ConflictListReq),
            typeof(ConscriptAck),
            typeof(ConscriptReq),
            typeof(CreateUnionReq),
            typeof(DealUnionInviteReq),
            typeof(DefenderInfoAck),
            typeof(DefenderInfoReq),
            typeof(DelCityNtf),
            typeof(DelFighterAck),
            typeof(DelFighterReq),
            typeof(DelHerosNtf),
            typeof(DelMarchNtf),
            typeof(DelTroopNtf),
            typeof(DelUnionMarkReq),
            typeof(DeleteMailAck),
            typeof(DeleteMailReq),
            typeof(DemiseUnionLeaderReq),
            typeof(DismantleCityAck),
            typeof(DismantleCityReq),
            typeof(DissolveUnionAck),
            typeof(DissolveUnionReq),
            typeof(DonateToUnionReq),
            typeof(DownGuardianHeroReq),
            typeof(DrillAck),
            typeof(DrillAttackTileReq),
            typeof(DrillBReportNtf),
            typeof(DrillIDAck),
            typeof(DrillIDReq),
            typeof(DrillReq),
            typeof(DrillSkipAnimationAck),
            typeof(DrillSkipAnimationReq),
            typeof(DrillStatisticAck),
            typeof(DrillStatisticReq),
            typeof(EpicAwardAck),
            typeof(EpicAwardReq),
            typeof(EpicNtf),
            typeof(F2EmptyTroopAck),
            typeof(F2EmptyTroopReq),
            typeof(FallenInfoNtf),
            typeof(FallenNoticeNtf),
            typeof(FallenPayRevoltResReq),
            typeof(FastLoginReq),
            typeof(FilterPosAck),
            typeof(FilterPosReq),
            typeof(FindUnionAck),
            typeof(FindUnionReq),
            typeof(FinishNbGuideAck),
            typeof(FinishNbGuideReq),
            typeof(ForceCollectTaxesReq),
            typeof(ForgetSkillAck),
            typeof(ForgetSkillReq),
            typeof(GachaAck),
            typeof(GachaListAck),
            typeof(GachaListReq),
            typeof(GachaReq),
            typeof(GetAllTaxAck),
            typeof(GetAllTaxReq),
            typeof(GetAttachmentAck),
            typeof(GetAttachmentReq),
            typeof(GetDealInfoAck),
            typeof(GetDealInfoReq),
            typeof(GetEpicInfoAck),
            typeof(GetEpicInfoReq),
            typeof(GetGsAck),
            typeof(GetGsReq),
            typeof(GetMailListAck),
            typeof(GetMailListReq),
            typeof(GetTaskAwardReq),
            typeof(GetUnionInfoListReq),
            typeof(GetUnionInfoReq),
            typeof(GiveupTileAck),
            typeof(GiveupTileReq),
            typeof(GiveupUnionTitleReq),
            typeof(GmAck),
            typeof(GmReq),
            typeof(GsLoginAck),
            typeof(GuardianTroopNtf),
            typeof(HeartBeatAck),
            typeof(HeartBeatReq),
            typeof(Hero2SkillAck),
            typeof(Hero2SkillReq),
            typeof(Hero2TroopAck),
            typeof(Hero2TroopReq),
            typeof(HeroAwakeAck),
            typeof(HeroAwakeReq),
            typeof(HeroListAck),
            typeof(HeroListReq),
            typeof(HeroPromoteAck),
            typeof(HeroPromoteReq),
            typeof(HeroSkillUpgradeAck),
            typeof(HeroSkillUpgradeReq),
            typeof(Heros2SkillExpAck),
            typeof(Heros2SkillExpReq),
            typeof(HerosNtf),
            typeof(InviteJoinUnionAck),
            typeof(InviteJoinUnionByNameReq),
            typeof(InviteJoinUnionReq),
            typeof(IsNearbyAck),
            typeof(IsNearbyReq),
            typeof(JoinUnionByNameReq),
            typeof(JoinUnionReq),
            typeof(KeyExchageAck),
            typeof(KeyExchageReq),
            typeof(KickoutNtf),
            typeof(LandListNtf),
            typeof(LandsBasicNtf),
            typeof(LandsBasicReq),
            typeof(LeaderBoardAck),
            typeof(LeaderBoardReq),
            typeof(LearnSkillAck),
            typeof(LearnSkillReq),
            typeof(LockHeroAck),
            typeof(LockHeroReq),
            typeof(LoginAck),
            typeof(LoginEventAwardReq),
            typeof(LogoutReq),
            typeof(MCityListAck),
            typeof(MCityListReq),
            typeof(MCityNtf),
            typeof(MFortressNtf),
            typeof(MailAwardsNtf),
            typeof(MailBoxNtf),
            typeof(MailListNtf),
            typeof(MapViewAck),
            typeof(MapViewReq),
            typeof(MarchAck),
            typeof(MarchInfoAck),
            typeof(MarchInfoReq),
            typeof(MarchReq),
            typeof(MarchsNtf),
            typeof(MarketBuyItemAck),
            typeof(MarketBuyItemReq),
            typeof(MarketBuyTimesAck),
            typeof(MarketBuyTimesReq),
            typeof(MarketsAck),
            typeof(MarketsNtf),
            typeof(MarketsReq),
            typeof(MoveMainCityReq),
            typeof(NCityListAck),
            typeof(NCityListReq),
            typeof(NewTroopAck),
            typeof(NewTroopReq),
            typeof(NpcCityInfoAck),
            typeof(NpcCityInfoNtf),
            typeof(NpcCityOccupyReq),
            typeof(PCityNtf),
            typeof(PCityReq),
            typeof(PNRegisterAck),
            typeof(PNRegisterReq),
            typeof(PayTokenAck),
            typeof(PayTokenReq),
            typeof(PlatformNtf),
            typeof(PlayCreateAck),
            typeof(PlayerChatAccountAck),
            typeof(PlayerChatAccountReq),
            typeof(PlayerInfoAck),
            typeof(PlayerInfoReq),
            typeof(PlayerLandsAck),
            typeof(PlayerLandsReq),
            typeof(PlayerUnionNtf),
            typeof(PushEventListAck),
            typeof(PushEventListReq),
            typeof(QueryPlayerAck),
            typeof(QueryPlayerReq),
            typeof(QueryPlayersByNameAck),
            typeof(QueryPlayersByNameReq),
            typeof(QuestionNaireAwardAck),
            typeof(QuestionNaireAwardReq),
            typeof(QuitUnionReq),
            typeof(ReadBReportAck),
            typeof(ReadBReportReq),
            typeof(ReadMailAck),
            typeof(ReadMailReq),
            typeof(RedifSpeedUpConscriptReq),
            typeof(RemoveRobberNtf),
            typeof(RemoveUnionMemberAck),
            typeof(RemoveUnionMemberReq),
            typeof(ResearchSkillAck),
            typeof(ResearchSkillReq),
            typeof(ResetAsgnAck),
            typeof(ResetAsgnReq),
            typeof(ResourceAck),
            typeof(ResourceNtf),
            typeof(ResourceReq),
            typeof(ReturnTroopAck),
            typeof(ReturnTroopReq),
            typeof(RobberNtf),
            typeof(RobotTaskAck),
            typeof(RobotTaskFinshReq),
            typeof(RobotTaskReq),
            typeof(SendMailAck),
            typeof(SendMailReq),
            typeof(SetUnionDescAck),
            typeof(SetUnionDescReq),
            typeof(SetUnionJoinLimitReq),
            typeof(SetUnionRelationReq),
            typeof(SkillExpNtf),
            typeof(SkillListAck),
            typeof(SkillListReq),
            typeof(SkillsNtf),
            typeof(StarMailAck),
            typeof(StarMailReq),
            typeof(SwapFighterAck),
            typeof(SwapFighterReq),
            typeof(SwapGuardianHeroReq),
            typeof(SwapUnionTitleReq),
            typeof(TaskActiveReq),
            typeof(TaskEventAwardReq),
            typeof(TaskListAck),
            typeof(TaskListReq),
            typeof(TasksNtf),
            typeof(TaxNtf),
            typeof(TaxReq),
            typeof(TestUnionReq),
            typeof(TileInfoAck),
            typeof(TileInfoReq),
            typeof(TilesNtf),
            typeof(TransResReq),
            typeof(TroopArrivedAtOnceReq),
            typeof(TroopListAck),
            typeof(TroopListReq),
            typeof(TroopNtf),
            typeof(UdidAck),
            typeof(UdidReq),
            typeof(UnLockHeroAck),
            typeof(UnLockHeroReq),
            typeof(UndoCollectBReportAck),
            typeof(UndoCollectBReportReq),
            typeof(UndoCollectLandReq),
            typeof(UndoConscriptAck),
            typeof(UndoConscriptReq),
            typeof(UndoGiveupTileAck),
            typeof(UndoGiveupTileReq),
            typeof(UnionFallenBroadcastNtf),
            typeof(UnionNtf),
            typeof(UnionPlayerBroadcastNtf),
            typeof(UnionRelationBroadcastNtf),
            typeof(UnstarMailAck),
            typeof(UnstarMailReq),
            typeof(UpGuardianHeroReq),
            typeof(UpdateNbGuideStepAck),
            typeof(UpdateNbGuideStepReq),
            typeof(UpdatePushEventsAck),
            typeof(UpdatePushEventsReq),
            typeof(UpdateTokenAck),
            typeof(UpdateTokenReq),
            typeof(UpdateUnfroceGuideAck),
            typeof(UpdateUnfroceGuideReq),
            typeof(UpgradeBuildAtOnceReq),
            typeof(UpgradeBuildReq),
            typeof(VisionViewReq),
            typeof(VisionsNtf),
       };

       private static readonly Dictionary<RuntimeTypeHandle, MessageParser> Parsers = new Dictionary<RuntimeTypeHandle, MessageParser>()
       {
            {typeof(AccountLinkAck).TypeHandle,AccountLinkAck.Parser },
            {typeof(AccountLinkReq).TypeHandle,AccountLinkReq.Parser },
            {typeof(AddUnionMarkReq).TypeHandle,AddUnionMarkReq.Parser },
            {typeof(AffairNtf).TypeHandle,AffairNtf.Parser },
            {typeof(AllotAsgnAck).TypeHandle,AllotAsgnAck.Parser },
            {typeof(AllotAsgnReq).TypeHandle,AllotAsgnReq.Parser },
            {typeof(ApplyUnionByNameReq).TypeHandle,ApplyUnionByNameReq.Parser },
            {typeof(ApplyUnionReq).TypeHandle,ApplyUnionReq.Parser },
            {typeof(AppointUnionMemberTitleReq).TypeHandle,AppointUnionMemberTitleReq.Parser },
            {typeof(ApproveApplyUnionReq).TypeHandle,ApproveApplyUnionReq.Parser },
            {typeof(AuthAck).TypeHandle,AuthAck.Parser },
            {typeof(AuthReq).TypeHandle,AuthReq.Parser },
            {typeof(AwardNtf).TypeHandle,AwardNtf.Parser },
            {typeof(BReportBasicAck).TypeHandle,BReportBasicAck.Parser },
            {typeof(BReportBasicReq).TypeHandle,BReportBasicReq.Parser },
            {typeof(BReportDetailAck).TypeHandle,BReportDetailAck.Parser },
            {typeof(BReportDetailNtf).TypeHandle,BReportDetailNtf.Parser },
            {typeof(BReportDetailReq).TypeHandle,BReportDetailReq.Parser },
            {typeof(BReportNtf).TypeHandle,BReportNtf.Parser },
            {typeof(BReportsAck).TypeHandle,BReportsAck.Parser },
            {typeof(BReportsReq).TypeHandle,BReportsReq.Parser },
            {typeof(BasicNtf).TypeHandle,BasicNtf.Parser },
            {typeof(BattleAwardNtf).TypeHandle,BattleAwardNtf.Parser },
            {typeof(BindPassportAck).TypeHandle,BindPassportAck.Parser },
            {typeof(BindPassportReq).TypeHandle,BindPassportReq.Parser },
            {typeof(BuildCityAck).TypeHandle,BuildCityAck.Parser },
            {typeof(BuildCityReq).TypeHandle,BuildCityReq.Parser },
            {typeof(CancelApplyUnionReq).TypeHandle,CancelApplyUnionReq.Parser },
            {typeof(CancelDemiseReq).TypeHandle,CancelDemiseReq.Parser },
            {typeof(CancelUpgradeBuildReq).TypeHandle,CancelUpgradeBuildReq.Parser },
            {typeof(ChangeAvatarAck).TypeHandle,ChangeAvatarAck.Parser },
            {typeof(ChangeAvatarReq).TypeHandle,ChangeAvatarReq.Parser },
            {typeof(ChangeIntroAck).TypeHandle,ChangeIntroAck.Parser },
            {typeof(ChangeIntroReq).TypeHandle,ChangeIntroReq.Parser },
            {typeof(ChangeNameAck).TypeHandle,ChangeNameAck.Parser },
            {typeof(ChangeNameCheckAck).TypeHandle,ChangeNameCheckAck.Parser },
            {typeof(ChangeNameCheckReq).TypeHandle,ChangeNameCheckReq.Parser },
            {typeof(ChangeNameReq).TypeHandle,ChangeNameReq.Parser },
            {typeof(CharCreateReq).TypeHandle,CharCreateReq.Parser },
            {typeof(CharLoginReq).TypeHandle,CharLoginReq.Parser },
            {typeof(CharacterCreateCheckAck).TypeHandle,CharacterCreateCheckAck.Parser },
            {typeof(CharacterCreateCheckReq).TypeHandle,CharacterCreateCheckReq.Parser },
            {typeof(ChatAccountNtf).TypeHandle,ChatAccountNtf.Parser },
            {typeof(ChatListReq).TypeHandle,ChatListReq.Parser },
            {typeof(ChatNtf).TypeHandle,ChatNtf.Parser },
            {typeof(ChatReq).TypeHandle,ChatReq.Parser },
            {typeof(ChatRoomNtf).TypeHandle,ChatRoomNtf.Parser },
            {typeof(CityInvincibleReq).TypeHandle,CityInvincibleReq.Parser },
            {typeof(CollectBReportAck).TypeHandle,CollectBReportAck.Parser },
            {typeof(CollectBReportReq).TypeHandle,CollectBReportReq.Parser },
            {typeof(CollectLandReq).TypeHandle,CollectLandReq.Parser },
            {typeof(CollectLandsNtf).TypeHandle,CollectLandsNtf.Parser },
            {typeof(CollectTaxesReq).TypeHandle,CollectTaxesReq.Parser },
            {typeof(CommonAck).TypeHandle,CommonAck.Parser },
            {typeof(ConflictListAck).TypeHandle,ConflictListAck.Parser },
            {typeof(ConflictListReq).TypeHandle,ConflictListReq.Parser },
            {typeof(ConscriptAck).TypeHandle,ConscriptAck.Parser },
            {typeof(ConscriptReq).TypeHandle,ConscriptReq.Parser },
            {typeof(CreateUnionReq).TypeHandle,CreateUnionReq.Parser },
            {typeof(DealUnionInviteReq).TypeHandle,DealUnionInviteReq.Parser },
            {typeof(DefenderInfoAck).TypeHandle,DefenderInfoAck.Parser },
            {typeof(DefenderInfoReq).TypeHandle,DefenderInfoReq.Parser },
            {typeof(DelCityNtf).TypeHandle,DelCityNtf.Parser },
            {typeof(DelFighterAck).TypeHandle,DelFighterAck.Parser },
            {typeof(DelFighterReq).TypeHandle,DelFighterReq.Parser },
            {typeof(DelHerosNtf).TypeHandle,DelHerosNtf.Parser },
            {typeof(DelMarchNtf).TypeHandle,DelMarchNtf.Parser },
            {typeof(DelTroopNtf).TypeHandle,DelTroopNtf.Parser },
            {typeof(DelUnionMarkReq).TypeHandle,DelUnionMarkReq.Parser },
            {typeof(DeleteMailAck).TypeHandle,DeleteMailAck.Parser },
            {typeof(DeleteMailReq).TypeHandle,DeleteMailReq.Parser },
            {typeof(DemiseUnionLeaderReq).TypeHandle,DemiseUnionLeaderReq.Parser },
            {typeof(DismantleCityAck).TypeHandle,DismantleCityAck.Parser },
            {typeof(DismantleCityReq).TypeHandle,DismantleCityReq.Parser },
            {typeof(DissolveUnionAck).TypeHandle,DissolveUnionAck.Parser },
            {typeof(DissolveUnionReq).TypeHandle,DissolveUnionReq.Parser },
            {typeof(DonateToUnionReq).TypeHandle,DonateToUnionReq.Parser },
            {typeof(DownGuardianHeroReq).TypeHandle,DownGuardianHeroReq.Parser },
            {typeof(DrillAck).TypeHandle,DrillAck.Parser },
            {typeof(DrillAttackTileReq).TypeHandle,DrillAttackTileReq.Parser },
            {typeof(DrillBReportNtf).TypeHandle,DrillBReportNtf.Parser },
            {typeof(DrillIDAck).TypeHandle,DrillIDAck.Parser },
            {typeof(DrillIDReq).TypeHandle,DrillIDReq.Parser },
            {typeof(DrillReq).TypeHandle,DrillReq.Parser },
            {typeof(DrillSkipAnimationAck).TypeHandle,DrillSkipAnimationAck.Parser },
            {typeof(DrillSkipAnimationReq).TypeHandle,DrillSkipAnimationReq.Parser },
            {typeof(DrillStatisticAck).TypeHandle,DrillStatisticAck.Parser },
            {typeof(DrillStatisticReq).TypeHandle,DrillStatisticReq.Parser },
            {typeof(EpicAwardAck).TypeHandle,EpicAwardAck.Parser },
            {typeof(EpicAwardReq).TypeHandle,EpicAwardReq.Parser },
            {typeof(EpicNtf).TypeHandle,EpicNtf.Parser },
            {typeof(F2EmptyTroopAck).TypeHandle,F2EmptyTroopAck.Parser },
            {typeof(F2EmptyTroopReq).TypeHandle,F2EmptyTroopReq.Parser },
            {typeof(FallenInfoNtf).TypeHandle,FallenInfoNtf.Parser },
            {typeof(FallenNoticeNtf).TypeHandle,FallenNoticeNtf.Parser },
            {typeof(FallenPayRevoltResReq).TypeHandle,FallenPayRevoltResReq.Parser },
            {typeof(FastLoginReq).TypeHandle,FastLoginReq.Parser },
            {typeof(FilterPosAck).TypeHandle,FilterPosAck.Parser },
            {typeof(FilterPosReq).TypeHandle,FilterPosReq.Parser },
            {typeof(FindUnionAck).TypeHandle,FindUnionAck.Parser },
            {typeof(FindUnionReq).TypeHandle,FindUnionReq.Parser },
            {typeof(FinishNbGuideAck).TypeHandle,FinishNbGuideAck.Parser },
            {typeof(FinishNbGuideReq).TypeHandle,FinishNbGuideReq.Parser },
            {typeof(ForceCollectTaxesReq).TypeHandle,ForceCollectTaxesReq.Parser },
            {typeof(ForgetSkillAck).TypeHandle,ForgetSkillAck.Parser },
            {typeof(ForgetSkillReq).TypeHandle,ForgetSkillReq.Parser },
            {typeof(GachaAck).TypeHandle,GachaAck.Parser },
            {typeof(GachaListAck).TypeHandle,GachaListAck.Parser },
            {typeof(GachaListReq).TypeHandle,GachaListReq.Parser },
            {typeof(GachaReq).TypeHandle,GachaReq.Parser },
            {typeof(GetAllTaxAck).TypeHandle,GetAllTaxAck.Parser },
            {typeof(GetAllTaxReq).TypeHandle,GetAllTaxReq.Parser },
            {typeof(GetAttachmentAck).TypeHandle,GetAttachmentAck.Parser },
            {typeof(GetAttachmentReq).TypeHandle,GetAttachmentReq.Parser },
            {typeof(GetDealInfoAck).TypeHandle,GetDealInfoAck.Parser },
            {typeof(GetDealInfoReq).TypeHandle,GetDealInfoReq.Parser },
            {typeof(GetEpicInfoAck).TypeHandle,GetEpicInfoAck.Parser },
            {typeof(GetEpicInfoReq).TypeHandle,GetEpicInfoReq.Parser },
            {typeof(GetGsAck).TypeHandle,GetGsAck.Parser },
            {typeof(GetGsReq).TypeHandle,GetGsReq.Parser },
            {typeof(GetMailListAck).TypeHandle,GetMailListAck.Parser },
            {typeof(GetMailListReq).TypeHandle,GetMailListReq.Parser },
            {typeof(GetTaskAwardReq).TypeHandle,GetTaskAwardReq.Parser },
            {typeof(GetUnionInfoListReq).TypeHandle,GetUnionInfoListReq.Parser },
            {typeof(GetUnionInfoReq).TypeHandle,GetUnionInfoReq.Parser },
            {typeof(GiveupTileAck).TypeHandle,GiveupTileAck.Parser },
            {typeof(GiveupTileReq).TypeHandle,GiveupTileReq.Parser },
            {typeof(GiveupUnionTitleReq).TypeHandle,GiveupUnionTitleReq.Parser },
            {typeof(GmAck).TypeHandle,GmAck.Parser },
            {typeof(GmReq).TypeHandle,GmReq.Parser },
            {typeof(GsLoginAck).TypeHandle,GsLoginAck.Parser },
            {typeof(GuardianTroopNtf).TypeHandle,GuardianTroopNtf.Parser },
            {typeof(HeartBeatAck).TypeHandle,HeartBeatAck.Parser },
            {typeof(HeartBeatReq).TypeHandle,HeartBeatReq.Parser },
            {typeof(Hero2SkillAck).TypeHandle,Hero2SkillAck.Parser },
            {typeof(Hero2SkillReq).TypeHandle,Hero2SkillReq.Parser },
            {typeof(Hero2TroopAck).TypeHandle,Hero2TroopAck.Parser },
            {typeof(Hero2TroopReq).TypeHandle,Hero2TroopReq.Parser },
            {typeof(HeroAwakeAck).TypeHandle,HeroAwakeAck.Parser },
            {typeof(HeroAwakeReq).TypeHandle,HeroAwakeReq.Parser },
            {typeof(HeroListAck).TypeHandle,HeroListAck.Parser },
            {typeof(HeroListReq).TypeHandle,HeroListReq.Parser },
            {typeof(HeroPromoteAck).TypeHandle,HeroPromoteAck.Parser },
            {typeof(HeroPromoteReq).TypeHandle,HeroPromoteReq.Parser },
            {typeof(HeroSkillUpgradeAck).TypeHandle,HeroSkillUpgradeAck.Parser },
            {typeof(HeroSkillUpgradeReq).TypeHandle,HeroSkillUpgradeReq.Parser },
            {typeof(Heros2SkillExpAck).TypeHandle,Heros2SkillExpAck.Parser },
            {typeof(Heros2SkillExpReq).TypeHandle,Heros2SkillExpReq.Parser },
            {typeof(HerosNtf).TypeHandle,HerosNtf.Parser },
            {typeof(InviteJoinUnionAck).TypeHandle,InviteJoinUnionAck.Parser },
            {typeof(InviteJoinUnionByNameReq).TypeHandle,InviteJoinUnionByNameReq.Parser },
            {typeof(InviteJoinUnionReq).TypeHandle,InviteJoinUnionReq.Parser },
            {typeof(IsNearbyAck).TypeHandle,IsNearbyAck.Parser },
            {typeof(IsNearbyReq).TypeHandle,IsNearbyReq.Parser },
            {typeof(JoinUnionByNameReq).TypeHandle,JoinUnionByNameReq.Parser },
            {typeof(JoinUnionReq).TypeHandle,JoinUnionReq.Parser },
            {typeof(KeyExchageAck).TypeHandle,KeyExchageAck.Parser },
            {typeof(KeyExchageReq).TypeHandle,KeyExchageReq.Parser },
            {typeof(KickoutNtf).TypeHandle,KickoutNtf.Parser },
            {typeof(LandListNtf).TypeHandle,LandListNtf.Parser },
            {typeof(LandsBasicNtf).TypeHandle,LandsBasicNtf.Parser },
            {typeof(LandsBasicReq).TypeHandle,LandsBasicReq.Parser },
            {typeof(LeaderBoardAck).TypeHandle,LeaderBoardAck.Parser },
            {typeof(LeaderBoardReq).TypeHandle,LeaderBoardReq.Parser },
            {typeof(LearnSkillAck).TypeHandle,LearnSkillAck.Parser },
            {typeof(LearnSkillReq).TypeHandle,LearnSkillReq.Parser },
            {typeof(LockHeroAck).TypeHandle,LockHeroAck.Parser },
            {typeof(LockHeroReq).TypeHandle,LockHeroReq.Parser },
            {typeof(LoginAck).TypeHandle,LoginAck.Parser },
            {typeof(LoginEventAwardReq).TypeHandle,LoginEventAwardReq.Parser },
            {typeof(LogoutReq).TypeHandle,LogoutReq.Parser },
            {typeof(MCityListAck).TypeHandle,MCityListAck.Parser },
            {typeof(MCityListReq).TypeHandle,MCityListReq.Parser },
            {typeof(MCityNtf).TypeHandle,MCityNtf.Parser },
            {typeof(MFortressNtf).TypeHandle,MFortressNtf.Parser },
            {typeof(MailAwardsNtf).TypeHandle,MailAwardsNtf.Parser },
            {typeof(MailBoxNtf).TypeHandle,MailBoxNtf.Parser },
            {typeof(MailListNtf).TypeHandle,MailListNtf.Parser },
            {typeof(MapViewAck).TypeHandle,MapViewAck.Parser },
            {typeof(MapViewReq).TypeHandle,MapViewReq.Parser },
            {typeof(MarchAck).TypeHandle,MarchAck.Parser },
            {typeof(MarchInfoAck).TypeHandle,MarchInfoAck.Parser },
            {typeof(MarchInfoReq).TypeHandle,MarchInfoReq.Parser },
            {typeof(MarchReq).TypeHandle,MarchReq.Parser },
            {typeof(MarchsNtf).TypeHandle,MarchsNtf.Parser },
            {typeof(MarketBuyItemAck).TypeHandle,MarketBuyItemAck.Parser },
            {typeof(MarketBuyItemReq).TypeHandle,MarketBuyItemReq.Parser },
            {typeof(MarketBuyTimesAck).TypeHandle,MarketBuyTimesAck.Parser },
            {typeof(MarketBuyTimesReq).TypeHandle,MarketBuyTimesReq.Parser },
            {typeof(MarketsAck).TypeHandle,MarketsAck.Parser },
            {typeof(MarketsNtf).TypeHandle,MarketsNtf.Parser },
            {typeof(MarketsReq).TypeHandle,MarketsReq.Parser },
            {typeof(MoveMainCityReq).TypeHandle,MoveMainCityReq.Parser },
            {typeof(NCityListAck).TypeHandle,NCityListAck.Parser },
            {typeof(NCityListReq).TypeHandle,NCityListReq.Parser },
            {typeof(NewTroopAck).TypeHandle,NewTroopAck.Parser },
            {typeof(NewTroopReq).TypeHandle,NewTroopReq.Parser },
            {typeof(NpcCityInfoAck).TypeHandle,NpcCityInfoAck.Parser },
            {typeof(NpcCityInfoNtf).TypeHandle,NpcCityInfoNtf.Parser },
            {typeof(NpcCityOccupyReq).TypeHandle,NpcCityOccupyReq.Parser },
            {typeof(PCityNtf).TypeHandle,PCityNtf.Parser },
            {typeof(PCityReq).TypeHandle,PCityReq.Parser },
            {typeof(PNRegisterAck).TypeHandle,PNRegisterAck.Parser },
            {typeof(PNRegisterReq).TypeHandle,PNRegisterReq.Parser },
            {typeof(PayTokenAck).TypeHandle,PayTokenAck.Parser },
            {typeof(PayTokenReq).TypeHandle,PayTokenReq.Parser },
            {typeof(PlatformNtf).TypeHandle,PlatformNtf.Parser },
            {typeof(PlayCreateAck).TypeHandle,PlayCreateAck.Parser },
            {typeof(PlayerChatAccountAck).TypeHandle,PlayerChatAccountAck.Parser },
            {typeof(PlayerChatAccountReq).TypeHandle,PlayerChatAccountReq.Parser },
            {typeof(PlayerInfoAck).TypeHandle,PlayerInfoAck.Parser },
            {typeof(PlayerInfoReq).TypeHandle,PlayerInfoReq.Parser },
            {typeof(PlayerLandsAck).TypeHandle,PlayerLandsAck.Parser },
            {typeof(PlayerLandsReq).TypeHandle,PlayerLandsReq.Parser },
            {typeof(PlayerUnionNtf).TypeHandle,PlayerUnionNtf.Parser },
            {typeof(PushEventListAck).TypeHandle,PushEventListAck.Parser },
            {typeof(PushEventListReq).TypeHandle,PushEventListReq.Parser },
            {typeof(QueryPlayerAck).TypeHandle,QueryPlayerAck.Parser },
            {typeof(QueryPlayerReq).TypeHandle,QueryPlayerReq.Parser },
            {typeof(QueryPlayersByNameAck).TypeHandle,QueryPlayersByNameAck.Parser },
            {typeof(QueryPlayersByNameReq).TypeHandle,QueryPlayersByNameReq.Parser },
            {typeof(QuestionNaireAwardAck).TypeHandle,QuestionNaireAwardAck.Parser },
            {typeof(QuestionNaireAwardReq).TypeHandle,QuestionNaireAwardReq.Parser },
            {typeof(QuitUnionReq).TypeHandle,QuitUnionReq.Parser },
            {typeof(ReadBReportAck).TypeHandle,ReadBReportAck.Parser },
            {typeof(ReadBReportReq).TypeHandle,ReadBReportReq.Parser },
            {typeof(ReadMailAck).TypeHandle,ReadMailAck.Parser },
            {typeof(ReadMailReq).TypeHandle,ReadMailReq.Parser },
            {typeof(RedifSpeedUpConscriptReq).TypeHandle,RedifSpeedUpConscriptReq.Parser },
            {typeof(RemoveRobberNtf).TypeHandle,RemoveRobberNtf.Parser },
            {typeof(RemoveUnionMemberAck).TypeHandle,RemoveUnionMemberAck.Parser },
            {typeof(RemoveUnionMemberReq).TypeHandle,RemoveUnionMemberReq.Parser },
            {typeof(ResearchSkillAck).TypeHandle,ResearchSkillAck.Parser },
            {typeof(ResearchSkillReq).TypeHandle,ResearchSkillReq.Parser },
            {typeof(ResetAsgnAck).TypeHandle,ResetAsgnAck.Parser },
            {typeof(ResetAsgnReq).TypeHandle,ResetAsgnReq.Parser },
            {typeof(ResourceAck).TypeHandle,ResourceAck.Parser },
            {typeof(ResourceNtf).TypeHandle,ResourceNtf.Parser },
            {typeof(ResourceReq).TypeHandle,ResourceReq.Parser },
            {typeof(ReturnTroopAck).TypeHandle,ReturnTroopAck.Parser },
            {typeof(ReturnTroopReq).TypeHandle,ReturnTroopReq.Parser },
            {typeof(RobberNtf).TypeHandle,RobberNtf.Parser },
            {typeof(RobotTaskAck).TypeHandle,RobotTaskAck.Parser },
            {typeof(RobotTaskFinshReq).TypeHandle,RobotTaskFinshReq.Parser },
            {typeof(RobotTaskReq).TypeHandle,RobotTaskReq.Parser },
            {typeof(SendMailAck).TypeHandle,SendMailAck.Parser },
            {typeof(SendMailReq).TypeHandle,SendMailReq.Parser },
            {typeof(SetUnionDescAck).TypeHandle,SetUnionDescAck.Parser },
            {typeof(SetUnionDescReq).TypeHandle,SetUnionDescReq.Parser },
            {typeof(SetUnionJoinLimitReq).TypeHandle,SetUnionJoinLimitReq.Parser },
            {typeof(SetUnionRelationReq).TypeHandle,SetUnionRelationReq.Parser },
            {typeof(SkillExpNtf).TypeHandle,SkillExpNtf.Parser },
            {typeof(SkillListAck).TypeHandle,SkillListAck.Parser },
            {typeof(SkillListReq).TypeHandle,SkillListReq.Parser },
            {typeof(SkillsNtf).TypeHandle,SkillsNtf.Parser },
            {typeof(StarMailAck).TypeHandle,StarMailAck.Parser },
            {typeof(StarMailReq).TypeHandle,StarMailReq.Parser },
            {typeof(SwapFighterAck).TypeHandle,SwapFighterAck.Parser },
            {typeof(SwapFighterReq).TypeHandle,SwapFighterReq.Parser },
            {typeof(SwapGuardianHeroReq).TypeHandle,SwapGuardianHeroReq.Parser },
            {typeof(SwapUnionTitleReq).TypeHandle,SwapUnionTitleReq.Parser },
            {typeof(TaskActiveReq).TypeHandle,TaskActiveReq.Parser },
            {typeof(TaskEventAwardReq).TypeHandle,TaskEventAwardReq.Parser },
            {typeof(TaskListAck).TypeHandle,TaskListAck.Parser },
            {typeof(TaskListReq).TypeHandle,TaskListReq.Parser },
            {typeof(TasksNtf).TypeHandle,TasksNtf.Parser },
            {typeof(TaxNtf).TypeHandle,TaxNtf.Parser },
            {typeof(TaxReq).TypeHandle,TaxReq.Parser },
            {typeof(TestUnionReq).TypeHandle,TestUnionReq.Parser },
            {typeof(TileInfoAck).TypeHandle,TileInfoAck.Parser },
            {typeof(TileInfoReq).TypeHandle,TileInfoReq.Parser },
            {typeof(TilesNtf).TypeHandle,TilesNtf.Parser },
            {typeof(TransResReq).TypeHandle,TransResReq.Parser },
            {typeof(TroopArrivedAtOnceReq).TypeHandle,TroopArrivedAtOnceReq.Parser },
            {typeof(TroopListAck).TypeHandle,TroopListAck.Parser },
            {typeof(TroopListReq).TypeHandle,TroopListReq.Parser },
            {typeof(TroopNtf).TypeHandle,TroopNtf.Parser },
            {typeof(UdidAck).TypeHandle,UdidAck.Parser },
            {typeof(UdidReq).TypeHandle,UdidReq.Parser },
            {typeof(UnLockHeroAck).TypeHandle,UnLockHeroAck.Parser },
            {typeof(UnLockHeroReq).TypeHandle,UnLockHeroReq.Parser },
            {typeof(UndoCollectBReportAck).TypeHandle,UndoCollectBReportAck.Parser },
            {typeof(UndoCollectBReportReq).TypeHandle,UndoCollectBReportReq.Parser },
            {typeof(UndoCollectLandReq).TypeHandle,UndoCollectLandReq.Parser },
            {typeof(UndoConscriptAck).TypeHandle,UndoConscriptAck.Parser },
            {typeof(UndoConscriptReq).TypeHandle,UndoConscriptReq.Parser },
            {typeof(UndoGiveupTileAck).TypeHandle,UndoGiveupTileAck.Parser },
            {typeof(UndoGiveupTileReq).TypeHandle,UndoGiveupTileReq.Parser },
            {typeof(UnionFallenBroadcastNtf).TypeHandle,UnionFallenBroadcastNtf.Parser },
            {typeof(UnionNtf).TypeHandle,UnionNtf.Parser },
            {typeof(UnionPlayerBroadcastNtf).TypeHandle,UnionPlayerBroadcastNtf.Parser },
            {typeof(UnionRelationBroadcastNtf).TypeHandle,UnionRelationBroadcastNtf.Parser },
            {typeof(UnstarMailAck).TypeHandle,UnstarMailAck.Parser },
            {typeof(UnstarMailReq).TypeHandle,UnstarMailReq.Parser },
            {typeof(UpGuardianHeroReq).TypeHandle,UpGuardianHeroReq.Parser },
            {typeof(UpdateNbGuideStepAck).TypeHandle,UpdateNbGuideStepAck.Parser },
            {typeof(UpdateNbGuideStepReq).TypeHandle,UpdateNbGuideStepReq.Parser },
            {typeof(UpdatePushEventsAck).TypeHandle,UpdatePushEventsAck.Parser },
            {typeof(UpdatePushEventsReq).TypeHandle,UpdatePushEventsReq.Parser },
            {typeof(UpdateTokenAck).TypeHandle,UpdateTokenAck.Parser },
            {typeof(UpdateTokenReq).TypeHandle,UpdateTokenReq.Parser },
            {typeof(UpdateUnfroceGuideAck).TypeHandle,UpdateUnfroceGuideAck.Parser },
            {typeof(UpdateUnfroceGuideReq).TypeHandle,UpdateUnfroceGuideReq.Parser },
            {typeof(UpgradeBuildAtOnceReq).TypeHandle,UpgradeBuildAtOnceReq.Parser },
            {typeof(UpgradeBuildReq).TypeHandle,UpgradeBuildReq.Parser },
            {typeof(VisionViewReq).TypeHandle,VisionViewReq.Parser },
            {typeof(VisionsNtf).TypeHandle,VisionsNtf.Parser },
       };

        public static MessageParser GetMessageParser(RuntimeTypeHandle typeHandle)
        {
            MessageParser messageParser;
            Parsers.TryGetValue(typeHandle, out messageParser);
            return messageParser;
        }

        public static Type GetProtoTypeByProtoId(uint protoId)
        {
            int index = _protoId.IndexOf(protoId);
            return _protoType[index];
        }

        public static uint GetProtoIdByProtoType(Type type)
        {
            int index = _protoType.IndexOf(type);
            return _protoId[index];
        }

        public static bool ContainProtoId(uint protoId)
        {
            if(_protoId.Contains(protoId))
            {
                return true;
            }
            return false;
        }

        public static bool ContainProtoType(Type type)
        {
            if(_protoType.Contains(type))
            {
                return true;
            }
            return false;
        }
    }
}