// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: def.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cspb {

  /// <summary>Holder for reflection information generated from def.proto</summary>
  public static partial class DefReflection {

    #region Descriptor
    /// <summary>File descriptor for def.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CglkZWYucHJvdG8SBGNzcGIq3kIKCEVSUl9DT0RFEhUKEUVSUl9DT0RFX05P",
            "X0VSUk9SEAASGQoVRVJSX0NPREVfSU5URVJOQUxfRVJSEAESEwoPRVJSX0NP",
            "REVfUEZfRVJSEAISHAoYRVJSX0NPREVfRVJSX1NFUlZFUl9EQVRFEAMSJAog",
            "RVJSX0NPREVfUEZfSU5WQUxJRF9BQ0NFU1NfVE9LRU4QBBIlCiFFUlJfQ09E",
            "RV9QRVJNSVNTSU9OX1ZFUklGWV9GQUlMRUQQBRIcChhFUlJfQ09ERV9FUlJf",
            "SUxMRUdBTF9SRVEQBhIlCiFFUlJfQ09ERV9PUF9FVF9OT1RfQkVMT05HX1RP",
            "X1lPVVIQBxInCiNFUlJfQ09ERV9QRl9DSEFSQUNURVJfQ1JFQVRFX0ZBSUxF",
            "RBAIEhwKGEVSUl9DT0RFX1BGX0xPR0lOX0ZBSUxFRBAJEiAKHEVSUl9DT0RF",
            "X1BGX0FDQ19MSU5LX0hBU0NIQVIQChIfChtFUlJfQ09ERV9QRl9BQ0NfTElO",
            "S19GQVVLRUQQCxImCiJFUlJfQ09ERV9QRl9BQ0NfSU5WQUxJREFDQ09VTlRU",
            "WVBFEAwSHQoZRVJSX0NPREVfUExBWUVSX05PVF9GT1VORBBlEiYKIkVSUl9D",
            "T0RFX1BMQVlFUl9OQU1FX0FMUkVBRFlfRVhJU1QQZhIiCh5FUlJfQ09ERV9Q",
            "TEFZRVJfTkFNRV9MRU5fTElNSVQQZxIhCh1FUlJfQ09ERV9QTEFZRVJfTkFN",
            "RV9CQURfV09SRBBoEhgKFEVSUl9DT0RFX0FVVEhfRkFJTEVEEGkSIgoeRVJS",
            "X0NPREVfQUNDT1VOVF9DUkVBVEVfRkFJTEVEEGoSHwobRVJSX0NPREVfUExB",
            "WUVSX05PVF9GT1VORF8yEGsSHgoaRVJSX0NPREVfQUNDT1VOVF9OT1RfRk9V",
            "TkQQbBIhCh1FUlJfQ09ERV9HQVRFX0FERF9ST0xFX0ZBSUxFRBBtEhsKF0VS",
            "Ul9DT0RFX0lOVkFMSURfREVWSUNFEG4SFwoTRVJSX0NPREVfQ0FOT1RfQklO",
            "RBBvEiQKIEVSUl9DT0RFX0RVUExJQ0FURV9DUkVBVEVfUExBWUVSEHASJgoi",
            "RVJSX0NPREVfTE9HSU5fV0FJVF9MT0dPVVRfVElNRU9VVBBxEiEKHUVSUl9D",
            "T0RFX0xPR0lOX1dJVEhfRVJSX1NUQVRFEHISGgoWRVJSX0NPREVfTklMQ0xJ",
            "RU5USU5GTxBzEh0KGUVSUl9DT0RFX1NFUlZFUl9OT1RfRk9VTkQQdBIiCh5F",
            "UlJfQ09ERV9DT05ORUNUX1NFUlZFUl9GQUlMRUQQdRIcChhFUlJfQ09ERV9E",
            "VVBMSUNBVEVfTE9HSU4QdhIfChtFUlJfQ09ERV9GQVNUTE9HSU5TRUNSRVRF",
            "UlIQdxIYChRFUlJfQ09ERV9GT1JCSURFRE1TRxB4Eh8KG0VSUl9DT0RFX1BM",
            "QVlFUk5BTUVfTk9DSEFORxB5EiIKHkVSUl9DT0RFX1BMQVlFUl9OQU1FX0xF",
            "Tl9TSE9SVBB6EhkKFEVSUl9DT0RFX0VSUl9DSVRZX0lEEOkHEhoKFUVSUl9D",
            "T0RFX0VSUl9IRVJPX1JJRBDqBxIkCh9FUlJfQ09ERV9IRVJPX0lTX0lOX09U",
            "SEVSX1RST09QEOsHEh0KGEVSUl9DT0RFX1BMQVlFUl9SRVNfTEFDSxDsBxIa",
            "ChVFUlJfQ09ERV9FUlJfQlVJTERfSUQQ7QcSJQogRVJSX0NPREVfQlVJTERf",
            "QUxSRUFEWV9NQVhfTEVWRUwQ7gcSHwoaRVJSX0NPREVfRVJSX0JVSUxEX1JF",
            "TFlfT04Q7wcSIwoeRVJSX0NPREVfQlVJTERfQUxSRUFEWV9VUEdSQURFEPAH",
            "EiUKIEVSUl9DT0RFX0JSRVBPUlRfQUxSRUFEWV9DT0xMRUNUEPEHEiIKHUVS",
            "Ul9DT0RFX0ZVTExfQ09MTEVDVF9CUkVQT1JUEPIHEiQKH0VSUl9DT0RFX1NL",
            "SUxMX0FMUkVBRFlfUkVTRUFSQ0gQ9AcSIAobRVJSX0NPREVfU0tJTExfSVNf",
            "SU5URUdSSVRZEPUHEiUKIEVSUl9DT0RFX0hFUk9fQ0FOTk9UX0xFQVJOX1NL",
            "SUxMEPYHEiYKIUVSUl9DT0RFX0hFUk9fQ0FOTk9UX0ZPUkdFVF9TS0lMTBD3",
            "BxIcChdFUlJfQ09ERV9FUlJfQlJFUE9SVF9JRBD4BxInCiJFUlJfQ09ERV9F",
            "UlJfSEVST19SRU1BSU5fQVNHTl9MQUNLEPkHEiYKIUVSUl9DT0RFX0hFUk9f",
            "QUxSRUFEWV9NQVhfQURWU1RBUhD6BxIlCiBFUlJfQ09ERV9DT05TVU1FX0hF",
            "Uk9fQ0FOTk9UX0RFTBD7BxIrCiZFUlJfQ09ERV9QUk9NT1RFX0NPTlNVTUVf",
            "SEVST19OT1RfU0FNRRD8BxIcChdFUlJfQ09ERV9IRVJPX0hBU19BV0FLRRD+",
            "BxIqCiVFUlJfQ09ERV9QTEFZRVJfQUxSRUFEWV9GSU5JU0hfTkVXQklFEIAI",
            "EikKJEVSUl9DT0RFX0FXQUtFX0NPTlNVTUVfU1RBUl9OT1RfU0FNRRCBCBIj",
            "Ch5FUlJfQ09ERV9DT05TVU1FX0hFUk9fSU5fVFJPT1AQgggSKAojRVJSX0NP",
            "REVfSFJFT19BV0FLRV9DT05TVU1FX0NOVF9FUlIQgwgSJgohRVJSX0NPREVf",
            "U0tJTExfSU5ERVhfT1VUX09GX1JBTkdFEIUIEiUKIEVSUl9DT0RFX1NLSUxM",
            "X0NBTk5PVF9CRV9MRUFSTkVEEIYIEicKIkVSUl9DT0RFX0lOREVYX0FMUkVB",
            "RFlfTEVBUk5fU0tJTEwQhwgSFwoSRVJSX0NPREVfUkVQRUFUX0lEEIgIEisK",
            "JkVSUl9DT0RFX0hFUk9fQUxSRUFEWV9MRUFSTl9USElTX1NLSUxMEIkIEhoK",
            "FUVSUl9DT0RFX0VSUl9TS0lMTF9JRBCKCBInCiJFUlJfQ09ERV9IRVJPX0tJ",
            "TkRfTk9UX01BVENIX1NLSUxMEIsIEi0KKEVSUl9DT0RFX0hFUk9fQ09OTk9U",
            "X1JFU0VBUkNIX1RISVNfU0tJTEwQjAgSHQoYRVJSX0NPREVfRVJSX1NLSUxM",
            "X0xFVkVMEI0IEiAKG0VSUl9DT0RFX0VSUl9TS0lMTF9FWFBfTEFDSxCOCBIh",
            "ChxFUlJfQ09ERV9IRVJPX0FMUkVBRFlfTE9DS0VEEI8IEiMKHkVSUl9DT0RF",
            "X0hFUk9fQUxSRUFEWV9VTkxPQ0tFRBCQCBIiCh1FUlJfQ09ERV9BTExPVF9B",
            "U0dOX1ZBTFVFX0VSUhCRCBIlCiBFUlJfQ09ERV9IRVJPX0xFVkVMX0NBTk5P",
            "VF9BV0FLRRCSCBIsCidFUlJfQ09ERV9GSVJTVF9TS0lMTF9MRVZFTF9DQU5O",
            "T1RfQVdBS0UQkwgSIQocRVJSX0NPREVfUExBWUVSX0RJQU1PTkRfTEFDSxCU",
            "CBInCiJFUlJfQ09ERV9SRVNFVF9BU0dOX1RZUEVfTk9UX01BVENIEJUIEiIK",
            "HUVSUl9DT0RFX0JVSUxEX0lTX05PVF9VUEdSQURFEJYIEiMKHkVSUl9DT0RF",
            "X0NPTExFQ1RfVEFYRVNfQ05UX01BWBCXCBIlCiBFUlJfQ09ERV9UUkFOU19S",
            "RVNfU1JDX0RFU1RfU0FNRRCYCBInCiJFUlJfQ09ERV9UUkFOU19SRVNfQ05U",
            "X0xFU1NfVEhBTl8wEJkIEikKJEVSUl9DT0RFX1BMQVlFUl9IQVZFX05PVF9U",
            "UkFOU19CVUlMRBCaCBIkCh9FUlJfQ09ERV9UUkFOU19SRVNfU1JDX0RFU1Rf",
            "RVJSEJsIEiAKG0VSUl9DT0RFX0ZVTExfQ09MTEVDVF9MQU5EUxCcCBIiCh1F",
            "UlJfQ09ERV9FUlJfUExBWUVSX0NPSU5fTEFDSxCdCBIeChlFUlJfQ09ERV9Q",
            "TEFZRVJfSEVST19GVUxMEJ4IEh8KGkVSUl9DT0RFX1BMQVlFUl9TS0lMTF9G",
            "VUxMEJ8IEiEKHEVSUl9DT0RFX05PVF9DT01QTEVBVEVEX1RBU0sQoAgSGAoT",
            "RVJSX0NPREVfRVJSX1RBU0tJRBChCBIcChdFUlJfQ09ERV9UQVNLX05PVF9F",
            "WElTVBCiCBIdChhFUlJfQ09ERV9FUlJfTkVYVF9UQVNLSUQQowgSIAobRVJS",
            "X0NPREVfVU5LTk9XTl9UQVNLX1BSSVpFEKQIEhsKFkVSUl9DT0RFX05PX0dP",
            "T0RTX05BTUUQpQgSGwoWRVJSX0NPREVfTEFDS19SRVNPVVJDRRCmCBIeChlF",
            "UlJfQ09ERV9JTlZBTElEX1BVUkNIQVNFEKcIEh0KGEVSUl9DT0RFX1dST05H",
            "X01BUktFVF9JRBCoCBIbChZFUlJfQ09ERV9NQVJLRVRfTE9DS0VEEKkIEh8K",
            "GkVSUl9DT0RFX1RBWF9USU1FX0lOVEVSVkFMEKoIEhwKF0VSUl9DT0RFX0dP",
            "T0RTX1NPTERfT1VUEKsIEh0KGEVSUl9DT0RFX1RSQURFX1pFUk9fUkFURRCs",
            "CBIZChRFUlJfQ09ERV9JTlZBTElEX1JFUxCtCBIWChFFUlJfQ09ERV9TQU1F",
            "X1JFUxCuCBImCiFFUlJfQ09ERV9NQVhfTUFSS0VUX1JFRlJFU0hfVElNRVMQ",
            "rwgSJAofRVJSX0NPREVfQlVJTERfVElMRV9MRVZFTF9MSU1JVBCwCBIqCiVF",
            "UlJfQ09ERV9QUk9NT1RFX0NPTlNVTUVfSEVST19DTlRfRVJSELEIEikKJEVS",
            "Ul9DT0RFX0ZPUkNFX0NPTExFQ1RfVEFYRVNfQ05UX01BWBCyCBInCiJFUlJf",
            "Q09ERV9OT1RfUkVRVUlSRV9GT1JDRV9DT0xMRUNUELMIEhgKE0VSUl9DT0RF",
            "X09SREVSX0xBQ0sQtAgSIAobRVJSX0NPREVfQVZBVEFSX1dST05HX0lOREVY",
            "ELUIEiAKG0VSUl9DT0RFX0lOVFJPX1dST05HX0xFTkdUSBC2CBIcChdFUlJf",
            "Q09ERV9JTlRST19CQURfV09SRBC3CBIcChdFUlJfQ09ERV9FUlJfUFVTSF9F",
            "VkVOVBC4CBIlCiBFUlJfQ09ERV9FUlJfR0FDSEFfRVJSX1BBQ0tBR0VJRBC5",
            "CBIbChZFUlJfQ09ERV9FUlJfR0FDSEFfRU5EEMcIEh0KGEVSUl9DT0RFX01B",
            "UktFVF9PTERfREFUQRDICBIjCh5FUlJfQ09ERV9VTklPTl9PUF9OT19BVVRI",
            "T1JJVFkQzAgSJgohRVJSX0NPREVfVU5JT05fTkFNRV9BTFJFQURZX0VYSVNU",
            "EM0IEiIKHUVSUl9DT0RFX1VOSU9OX05BTUVfTEVOX0xJTUlUEM4IEiEKHEVS",
            "Ul9DT0RFX1VOSU9OX05BTUVfQkFEX1dPUkQQzwgSHQoYRVJSX0NPREVfVU5J",
            "T05fTk9UX0VYSVNUENAIEiEKHEVSUl9DT0RFX1VOSU9OX0FMUkVBRFlfQVBQ",
            "TFkQ0QgSHQoYRVJSX0NPREVfVU5JT05fTk9UX0FQUExZENMIEiQKH0VSUl9D",
            "T0RFX1VOSU9OX01FTUJFUl9OT1RfRVhJU1QQ1AgSIwoeRVJSX0NPREVfVU5J",
            "T05fVElUTEVfTk9UX0VYSVNUENUIEiIKHUVSUl9DT0RFX1VOSU9OX0NBTk5P",
            "VF9BUFBPSU5UENYIEiEKHEVSUl9DT0RFX1VOSU9OX0NBTk5PVF9SRU1PVkUQ",
            "1wgSIQocRVJSX0NPREVfVU5JT05fQ0FOTk9UX0RFTUlTRRDYCBIhChxFUlJf",
            "Q09ERV9VTklPTl9RVUlUX0NPT0xET1dOENkIEiEKHEVSUl9DT0RFX1VOSU9O",
            "X0FQUExZX01BWF9OVU0Q2ggSHwoaRVJSX0NPREVfVU5JT05fTUVNQkVSX0ZV",
            "TEwQ2wgSIwoeRVJSX0NPREVfVU5JT05fSk9JTl9XUk9OR19BUkVBENwIEh8K",
            "GkVSUl9DT0RFX1VOSU9OX0pPSU5fRk9SQklEEN0IEisKJkVSUl9DT0RFX1VO",
            "SU9OX1BMQVlFUl9BTFJFQURZX0lOX1VOSU9OEN4IEioKJUVSUl9DT0RFX1VO",
            "SU9OX0NSRUFURV9NQUlOX0NJVFlfTElNSVQQ3wgSKQokRVJSX0NPREVfVU5J",
            "T05fQ1JFQVRFX1JFU19DT0lOX0xJTUlUEOAIEiIKHUVSUl9DT0RFX1VOSU9O",
            "X1RJVExFX05VTV9GVUxMEOEIEh4KGUVSUl9DT0RFX1VOSU9OX05FRURfQVBQ",
            "TFkQ4ggSHwoaRVJSX0NPREVfVU5JT05fQ0FOTk9UX0pPSU4Q4wgSJAofRVJS",
            "X0NPREVfVU5JT05fV1JPTkdfSk9JTl9MSU1JVBDkCBIhChxFUlJfQ09ERV9V",
            "TklPTl9DQU5OT1RfRE9OQVRFEOUIEiIKHUVSUl9DT0RFX1VOSU9OX1dST05H",
            "X1JFTEFUSU9OEOYIEiUKIEVSUl9DT0RFX1VOSU9OX1JFTEFUSU9OX05VTV9G",
            "VUxMEOcIEioKJUVSUl9DT0RFX1VOSU9OX1JFTEFUSU9OX0NBTk5PVF9DSEFO",
            "R0UQ6AgSIQocRVJSX0NPREVfVU5JT05fTUFSS19OVU1fRlVMTBDpCBInCiJF",
            "UlJfQ09ERV9VTklPTl9NQVJLX05BTUVfTEVOX0xJTUlUEOoIEioKJUVSUl9D",
            "T0RFX1VOSU9OX01BUktfQ09OVEVOdF9MRU5fTElNSVQQ6wgSIQocRVJSX0NP",
            "REVfVU5JT05fTUFSS19CQURfV09SRBDsCBIiCh1FUlJfQ09ERV9VTklPTl9E",
            "RVNDX0xFTl9MSU1JVBDtCBIhChxFUlJfQ09ERV9VTklPTl9ERVNDX0JBRF9X",
            "T1JEEO4IEh0KGEVSUl9DT0RFX1VOSU9OX05PX0RFTUlTRRDvCBIlCiBFUlJf",
            "Q09ERV9VTklPTl9DQU5OT1RfU1dBUF9USVRMRRDwCBIjCh5FUlJfQ09ERV9V",
            "TklPTl9DQU5OT1RfRElTU09MVkUQ8QgSHwoaRVJSX0NPREVfRkFMTEVOX05P",
            "VF9GQUxMRU4Q9AgSKgolRVJSX0NPREVfRkFMTEVOX0NBTk5PVF9QQVlfUkVW",
            "T0xUX1JFUxD1CBIgChtFUlJfQ09ERV9EUklMTF9JRF9OT1RfRVhJU1QQ/ggS",
            "IgodRVJSX0NPREVfRFJJTExfSURfSVNfTk9UX09QRU4Q/wgSJgohRVJSX0NP",
            "REVfRFJJTExfSURfSVNfQUxSRUFEWV9PUEVOEIAJEiUKIEVSUl9DT0RFX0RS",
            "SUxMX05PX01FRVRfQ09ORElUSU9OEIEJEiQKH0VSUl9DT0RFX0RSSUxMX0NB",
            "TlRfQVRUQUNLX1RJTEUQggkSKgolRVJSX0NPREVfRFJJTExfVElMRV9JU19B",
            "TFJFQURZX09DQ1VQWRCDCRIkCh9FUlJfQ09ERV9EUklMTF9JTlZBTElEX1RJ",
            "TEVfUE9TEIQJEiYKIUVSUl9DT0RFX0RSSUxMX0hFUk9TX1dST05HX05VTUJF",
            "UhCFCRIiCh1FUlJfQ09ERV9EUklMTF9IRVJPX05PVF9FWElTVBCGCRIoCiNF",
            "UlJfQ09ERV9EUklMTF9IRVJPU19OT1RfUkVBQ0hfVElMRRCHCRIiCh1FUlJf",
            "Q09ERV9EUklMTF9OT19FTk9VR0hfQ09JThCICRIbChZFUlJfQ09ERV9EUklM",
            "TF9OT19QQVNTEIkJEhkKFEVSUl9DT0RFX0RSSUxMX0lOX0NEEIoJEiIKHUVS",
            "Ul9DT0RFX0RSSUxMX1RPT19ESUZGSUNVTFRZEIsJEiYKIUVSUl9DT0RFX0RS",
            "SUxMX1RVVE9SSUFMX0NBTlRfU0tJUBCMCRIpCiRFUlJfQ09ERV9EUklMTF9U",
            "VVRPUklBTF9OT19TVEFUSVNUSUMQjQkSIgodRVJSX0NPREVfRFJJTExfRFVQ",
            "TElDQVRFX0hFUk8QjgkSHgoZRVJSX0NPREVfQlVJTERfUVVFVUVfRlVMTBCw",
            "CRIXChJFUlJfQ09ERV9MT0dJTl9EQVkQsQkSGQoURVJSX0NPREVfRVJSX1RB",
            "U0tfSUQQsgkSJwoiRVJSX0NPREVfRVJSX1RBU0tfQUxSRUFEWV9DT01QTEVU",
            "RRCzCRIkCh9FUlJfQ09ERV9FUlJfVEFTS19BTFJFQURZX0FXQVJEELQJEiIK",
            "HUVSUl9DT0RFX0VSUl9MT0dJTl9FVkVOVF9NT1JFELUJEiMKHkVSUl9DT0RF",
            "X0VSUl9MT0dJTl9FVkVOVF9BV0FSRBC2CRIfChpFUlJfQ09ERV9NQUlMX05P",
            "VF9JTl9VTklPThC6CRIiCh1FUlJfQ09ERV9BTExPQ19NQVBfUE9TX0ZBSUxF",
            "RBDRDxIcChdFUlJfQ09ERV9OT1RfVElMRV9PV05FUhDSDxIdChhFUlJfQ09E",
            "RV9USUxFX09OX1BST1RFQ1QQ0w8SHwoaRVJSX0NPREVfVElMRV9JU19HSVZJ",
            "TkdfVVAQ1A8SGQoURVJSX0NPREVfSU5WQUxJRF9QT1MQ1Q8SIAobRVJSX0NP",
            "REVfVElMRV9OT1RfR0lWSU5HX1VQENYPEh4KGUVSUl9DT0RFX0lOVkFMSURf",
            "R1JJRF9QT1MQ1w8SHAoXRVJSX0NPREVfVE9PX01VQ0hfR1JJRFMQ2A8SIAob",
            "RVJSX0NPREVfTUFSQ0hfUkVRX1RZUEVfRVJSENkPEiMKHkVSUl9DT0RFX0FU",
            "VEFDS19OT19ORUFSQllfVElMRRDaDxIgChtFUlJfQ09ERV9USUxFX0NBTk5P",
            "VF9BVFRBQ0sQ2w8SIwoeRVJSX0NPREVfUExBWUVSX05PVF9USUxFX09XTkVS",
            "ENwPEhoKFUVSUl9DT0RFX0VSUl9UUk9PUF9JRBDdDxIhChxFUlJfQ09ERV9I",
            "RVJPX0lTTk9UX0lOX1RST09QEN4PEiEKHEVSUl9DT0RFX0ZJR0hURVJfTlVN",
            "X0xJTUlURUQQ3w8SKQokRVJSX0NPREVfVFJPT1BfQ1RMX0NPTlNDUklQVF9G",
            "SUdIVEVSEOAPEhoKFUVSUl9DT0RFX0VSUl9NQVJDSF9JRBDhDxIjCh5FUlJf",
            "Q09ERV9SRVRVUk5fTUFSQ0hfRVJSX1RJTUUQ4g8SGgoVRVJSX0NPREVfRVJS",
            "X1RST09QX05PEOMPEh0KGEVSUl9DT0RFX1RST09QX05PVF9GT1VORBDkDxId",
            "ChhFUlJfQ09ERV9FUlJfVFJPT1BfU1RBVEUQ5Q8SIgodRVJSX0NPREVfRklH",
            "SFRFUl9TRVJJT1VTX0hVUlQQ5g8SHQoYRVJSX0NPREVfRVJSX0ZJR0hURVJf",
            "UE9TEOcPEiIKHUVSUl9DT0RFX1RST09QU19JTl9UV09fQ0lUSUVTEOgPEiIK",
            "HUVSUl9DT0RFX0ZVTExfQ09OU0NSSVBUX1FVRVVFEOkPEh4KGUVSUl9DT0RF",
            "X0hFUk9fRU5FUkdZX0xBQ0sQ6g8SIQocRVJSX0NPREVfVFJPT1BfQ0FOTk9U",
            "X1JFVFVSThDrDxIiCh1FUlJfQ09ERV9UUk9PUF9JU19OT1RfSU5fQ0lUWRDs",
            "DxIbChZFUlJfQ09ERV9UUkFJTl9DTlRfRVJSEO0PEh0KGEVSUl9DT0RFX0NJ",
            "VFlfUkVESUZfTEFDSxDuDxIpCiRFUlJfQ09ERV9SRURJRl9DT05TQ1JJUFRf",
            "UkVRX0NOVF9FUlIQ7w8SHAoXRVJSX0NPREVfQ0lUWV9DT1NUX0xBQ0sQ8A8S",
            "JgohRVJSX0NPREVfRklHSFRFUl9IUF9NT1JFX1RIQU5fTUFYEPEPEiMKHkVS",
            "Ul9DT0RFX0NPTlNDUklQVF9SRVFfQ05UX0VSUhDyDxImCiFFUlJfQ09ERV9G",
            "SUdIVEVSX0lTX05PVF9DT05TQ1JJUFQQ8w8SKAojRVJSX0NPREVfUkVUVVJO",
            "X1RST09QX1JFUV9TVEFURV9FUlIQ9A8SKgolRVJSX0NPREVfVFJPT1BTX0NP",
            "Tk5PVF9IQVZFX1NBTUVfSEVSTxD1DxIlCiBFUlJfQ09ERV9GSUxURVJfUkFE",
            "SVVTX1RPT19MQVJHRRD2DxIjCh5FUlJfQ09ERV9QTEFZRVJfTk9UX0NJVFlf",
            "T1dORVIQ9w8SJwoiRVJSX0NPREVfVFJBTlNGRVJfQ0lUWV9UUk9PUFNfRlVM",
            "TBD4DxIpCiRFUlJfQ09ERV9UUkFOU0ZFUl9QT1NfU0FNRV9UUk9PUF9QT1MQ",
            "+Q8SIwoeRVJSX0NPREVfUE9TX0NPTk5PVF9CVUlMRF9DSVRZEPoPEikKJEVS",
            "Ul9DT0RFX0NPTk5PVF9CVUlMRF9USElTX0NJVFlfVFlQRRD7DxIdChhFUlJf",
            "Q09ERV9CVUlMRF9DSVRZX0ZVTEwQ/A8SJwoiRVJSX0NPREVfVElMRV9FVFlQ",
            "RV9JU19OT1RfTk9USElORxD9DxIoCiNFUlJfQ09ERV9DT05OT1RfRElTTUFO",
            "VExFX0NJVFlfVFlQRRD+DxIpCiRFUlJfQ09ERV9DSVRZX1NUQVRFX0NPTk5P",
            "VF9ESVNNQU5UTEUQ/w8SHgoZRVJSX0NPREVfR0lWRVVQX1NQX0VOVElUWRCA",
            "EBInCiJFUlJfQ09ERV9GSUdIVEVSX0FMUkVBRFlfQ09OU0NSSVBUEIEQEiQK",
            "H0VSUl9DT0RFX01BUkNIX0NPTlNDUklQVF9GSUdIVEUQghASHwoaRVJSX0NP",
            "REVfT0xEX0ZPUlRSRVNTX0ZVTEwQgxASJAofRVJSX0NPREVfT0xEX0ZPUlRS",
            "RVNTX05PVF9FWElTVBCEEBImCiFFUlJfQ09ERV9UUk9PUF9ORUVEX0ZJUlNU",
            "X0ZJR0hURVIQhRASIwoeRVJSX0NPREVfQ0FOTk9UX01PVkVfQ0lUWV9IRVJF",
            "EIYQEiMKHkVSUl9DT0RFX01PVkVfQ0lUWV9CVUlMRF9RVUVVRRCHEBInCiJF",
            "UlJfQ09ERV9NT1ZFX0NJVFlfQ09OU0NSSVBUX1FVRVVFEIgQEh4KGUVSUl9D",
            "T0RFX01PVkVfQ0lUWV9GQUxMRU4QiRASIQocRVJSX0NPREVfTU9WRV9DSVRZ",
            "X0RJU01BTlRMRRCKEBIgChtFUlJfQ09ERV9DSVRZX0lOX0lOVklOQ0lCTEUQ",
            "ixASIwoeRVJSX0NPREVfQ0lUWV9JTlZJTkNJQkxFX1NUQVRFEIwQEh8KGkVS",
            "Ul9DT0RFX0VQSUNfQ0FOTk9UX0FXQVJEEI0QEiYKIUVSUl9DT0RFX0VQSUNf",
            "UExBWUVSX0NBTk5PVF9BV0FSRBCOEBIhChxFUlJfQ09ERV9QUkVTVElHRV9O",
            "T1RfRU5PVUdIEI8QKq0CCgtFTlRJVFlfVFlQRRIXChNFTlRJVFlfVFlQRV9O",
            "T1RISU5HEAASGQoVRU5USVRZX1RZUEVfTUFJTl9DSVRZEAESGAoURU5USVRZ",
            "X1RZUEVfQ0lUWV9EU1QQAhIYChRFTlRJVFlfVFlQRV9DSVRZX1NVQhADEhkK",
            "FUVOVElUWV9UWVBFX1BGT1JUUkVTUxAEEhUKEUVOVElUWV9UWVBFX1JVSU5T",
            "EAUSGQoVRU5USVRZX1RZUEVfTkZPUlRSRVNTEAYSGAoURU5USVRZX1RZUEVf",
            "TlBDX0NJVFkQBxIcChhFTlRJVFlfVFlQRV9OUENfQ0lUWV9EU1QQChIXChNF",
            "TlRJVFlfVFlQRV9URVJSSUFOEAsSGAoURU5USVRZX1RZUEVfTlBDX0dBVEUQ",
            "DCqrAQoJQ0lUWV9UWVBFEhEKDUNJVFlfVFlQRV9FUlIQABIWChJDSVRZX1RZ",
            "UEVfTUFJTkNJVFkQARIVChFDSVRZX1RZUEVfU1VCQ0lUWRADEhcKE0NJVFlf",
            "VFlQRV9QRk9SVFJFU1MQBBITCg9DSVRZX1RZUEVfUlVJTlMQBRIXChNDSVRZ",
            "X1RZUEVfTkZPUlRSRVNTEAYSFQoRQ0lUWV9UWVBFX05QQ0NJVFkQByqvAQoK",
            "Q0lUWV9TVEFURRIUChBDSVRZX1NUQVRFX0JVSUxEEAASFQoRQ0lUWV9TVEFU",
            "RV9OT1JNQUwQARIYChRDSVRZX1NUQVRFX0RJU01BTlRMRRACEiEKHUNJVFlf",
            "U1RBVEVfSU5WSU5DSUJMRV9QUkVQQVJFEAMSGQoVQ0lUWV9TVEFURV9JTlZJ",
            "TkNJQkxFEAQSHAoYQ0lUWV9TVEFURV9JTlZJTkNJQkxFX0NEEAUq7QEKC1RS",
            "T09QX1NUQVRFEhYKElRST09QX1NUQVRFX0lOQ0lUWRAAEhUKEVRST09QX1NU",
            "QVRFX01BUkNIEAESGQoVVFJPT1BfU1RBVEVfRFJBV19SRVNUEAISGAoUVFJP",
            "T1BfU1RBVEVfR0FSUklTT04QAxIWChJUUk9PUF9TVEFURV9SRVRVUk4QBBIV",
            "ChFUUk9PUF9TVEFURV9UUkFJThAFEhcKE1RST09QX1NUQVRFX0NPTExFQ1QQ",
            "BhIYChRUUk9PUF9TVEFURV9UUkFOU0ZFUhAHEhgKFFRST09QX1NUQVRFX0lO",
            "QkFUVExFEAgq6QIKEFRJTEVfQUNUSU9OX1RZUEUSGAoUVElMRV9BQ1RJT05f",
            "VFlQRV9FUlIQABIbChdUSUxFX0FDVElPTl9UWVBFX0FUVEFDSxABEh0KGVRJ",
            "TEVfQUNUSU9OX1RZUEVfR0FSUklTT04QAhIcChhUSUxFX0FDVElPTl9UWVBF",
            "X01PUFBJTkcQAxIaChZUSUxFX0FDVElPTl9UWVBFX1RSQUlOEAQSHAoYVElM",
            "RV9BQ1RJT05fVFlQRV9DT0xMRUNUEAUSHgoaVElMRV9BQ1RJT05fVFlQRV9E",
            "UkFXX1JFU1QQBhIdChlUSUxFX0FDVElPTl9UWVBFX1RSQU5TRkVSEAcSHAoY",
            "VElMRV9BQ1RJT05fVFlQRV9SRVRSRUFUEAgSIwofVElMRV9BQ1RJT05fVFlQ",
            "RV9SRVRSRUFUX09OX1dBWRAJEiUKIVRJTEVfQUNUSU9OX1RZUEVfUkVUUkVB",
            "VF9UUkFOU0ZFUhAKKuoBCglJVEVNX1RZUEUSEQoNSVRFTV9UWVBFX0VSUhAA",
            "EhUKEUlURU1fVFlQRV9ESUFNT05EEAESEgoOSVRFTV9UWVBFX0NPSU4QAhIW",
            "ChJJVEVNX1RZUEVfUkVTT1VSQ0UQAxISCg5JVEVNX1RZUEVfSEVSTxAEEhMK",
            "D0lURU1fVFlQRV9TS0lMTBAFEhcKE0lURU1fVFlQRV9TS0lMTF9FWFAQBxIX",
            "ChNJVEVNX1RZUEVfU0tJTExfUFJPEAgSFwoTSVRFTV9UWVBFX0dBQ0hBX1BL",
            "RxAJEhMKD0lURU1fVFlQRV9SRURJRhAKKpgBCgtSRVNPVVJDRV9JRBIQCgxS",
            "RVNPVVJDRV9FUlIQABIRCg1SRVNPVVJDRV9GT09EEAESEgoOUkVTT1VSQ0Vf",
            "U1RPTkUQAhIRCg1SRVNPVVJDRV9XT09EEAMSEgoOUkVTT1VSQ0VfU1RFRUwQ",
            "BBIVChFSRVNPVVJDRV9QUkVTSVRHRRAFEhIKDlJFU09VUkNFX09SREVSEAYq",
            "vQEKB01DX1RZUEUSEgoOTUFJTF9UWVBFX05PTkUQABIUChBNQUlMX1RZUEVf",
            "UExBWUVSEAESFAoQTUFJTF9UWVBFX1NFUlZFUhACEhMKD01BSUxfVFlQRV9V",
            "TklPThADEhQKEE1BSUxfVFlQRV9TWVNURU0QBBIXChNDSEFUX0NIQU5ORUxf",
            "UExBWUVSEAoSFgoSQ0hBVF9DSEFOTkVMX1dPUkxEEAsSFgoSQ0hBVF9DSEFO",
            "TkVMX1VOSU9OEAwqQgoMUkVGUkVTSF9UWVBFEhAKDFJFRlJFU0hfTk9ORRAA",
            "Eg8KC1JFRlJFU0hfQUxMEAESDwoLUkVGUkVTSF9JTkMQAiojCgtDSEFUX1NU",
            "QVRVUxIKCgZVTlJFQUQQABIICgRSRUFEEAEqJwoMTE9HSU5fQUNUSU9OEgkK",
            "BUxPR0lOEAASDAoIUkVHSVNURVIQASrPAQoQVU5JT05fVElUTEVfVFlQRRIa",
            "ChZVTklPTl9USVRMRV9OT1RfTUVNQkVSEAASFgoSVU5JT05fVElUTEVfTEVB",
            "REVSEAESHQoZVU5JT05fVElUTEVfREVQVVRZX0xFQURFUhACEhsKF1VOSU9O",
            "X1RJVExFX0NPTU1BTkRFUl9BEAMSGwoXVU5JT05fVElUTEVfQ09NTUFOREVS",
            "X0IQBBIWChJVTklPTl9USVRMRV9NRU1CRVIQBRIWChJVTklPTl9USVRMRV9C",
            "QU5ORUQQBirSBQoNVU5JT05fT1BfVFlQRRIXChNVTklPTl9PUF9ET19OT1RI",
            "SU5HEAASGQoVVU5JT05fT1BfQ1JFQVRFX1VOSU9OEAESIAocVU5JT05fT1Bf",
            "R0VUX1VOSU9OX0lORk9fTElTVBACEhgKFFVOSU9OX09QX0FQUExZX1VOSU9O",
            "EAMSHwobVU5JT05fT1BfQ0FOQ0VMX0FQUExZX1VOSU9OEAQSFwoTVU5JT05f",
            "T1BfSk9JTl9VTklPThAFEhsKF1VOSU9OX09QX0RJU1NPTFZFX1VOSU9OEGUS",
            "EwoPVU5JT05fT1BfREVNSVNFEGYSGQoVVU5JT05fT1BfU0VUX1JFTEFUSU9O",
            "EGcSGgoWVU5JT05fT1BfQVBQUk9WRV9BUFBMWRBpEhoKFlVOSU9OX09QX1JF",
            "TU9WRV9NRU1CRVIQahIbChdVTklPTl9PUF9TRVRfSk9JTl9MSU1JVBBrEhsK",
            "F1VOSU9OX09QX1NFVF9VTklPTl9ERVNDEGwSFQoRVU5JT05fT1BfQUREX01B",
            "UksQbhIbChdVTklPTl9PUF9BUFBPSU5UX01FTUJFUhBvEhkKFVVOSU9OX09Q",
            "X0dJVkVVUF9USVRMRRByEhsKF1VOSU9OX09QX0dFVF9VTklPTl9JTkZPEHQS",
            "FwoTVU5JT05fT1BfUVVJVF9VTklPThB6Eh4KGlVOSU9OX09QX0lOVklURV9K",
            "T0lOX1VOSU9OEHsSGAoUVU5JT05fT1BfREVBTF9JTlZJVEUQfBIXChNVTklP",
            "Tl9PUF9GSU5EX1VOSU9OEH0SEwoPVU5JT05fT1BfRE9OQVRFEH4SFQoRVU5J",
            "T05fT1BfREVMX01BUksQfxIYChNVTklPTl9PUF9TV0FQX1RJVExFEIABEhsK",
            "FlVOSU9OX09QX0NBTkNFTF9ERU1JU0UQgQESHQoYVU5JT05fT1BfU0VORF9V",
            "TklPTl9NQUlMEIIBKoEBChBVTklPTl9KT0lOX0xJTUlUEhcKE1VOSU9OX0pP",
            "SU5fTk9fTElNSVQQABIZChVVTklPTl9KT0lOX05FRURfQVBQTFkQARIiCh5V",
            "TklPTl9KT0lOX05PX0FQUExZX1dJVEhfTElNSVQQAhIVChFVTklPTl9KT0lO",
            "X0ZPUkJJRBADKmcKE1VOSU9OX1JFTEFUSU9OX1RZUEUSFwoTVU5JT05fUkVM",
            "QVRJT05fTk9ORRAAEhsKF1VOSU9OX1JFTEFUSU9OX0ZSSUVORExZEAESGgoW",
            "VU5JT05fUkVMQVRJT05fSE9TVElMRRACKmgKDlVOSU9OX0xPR19UWVBFEhMK",
            "D1VOSU9OX0xPR19FVkVOVBAAEhQKEFVOSU9OX0xPR19NRU1CRVIQARITCg9V",
            "TklPTl9MT0dfRklHSFQQAhIWChJVTklPTl9MT0dfUkVMQVRJT04QAypvChRV",
            "TklPTl9MT0dfRVZFTlRfVFlQRRIZChVVTklPTl9MT0dfRVZFTlRfU0VUVVAQ",
            "ABIbChdVTklPTl9MT0dfRVZFTlRfTEVWRUxVUBABEh8KG1VOSU9OX0xPR19F",
            "VkVOVF9DTE9TRV9BUFBMWRACKpoCChVVTklPTl9MT0dfTUVNQkVSX1RZUEUS",
            "GQoVVU5JT05fTE9HX01FTUJFUl9KT0lOEAASHAoYVU5JT05fTE9HX01FTUJF",
            "Ul9BUFBPSU5UEAESHAoYVU5JT05fTE9HX01FTUJFUl9ESVNNSVNTEAISGQoV",
            "VU5JT05fTE9HX01FTUJFUl9RVUlUEAMSGwoXVU5JT05fTE9HX01FTUJFUl9S",
            "RU1PVkUQBBInCiNVTklPTl9MT0dfTUVNQkVSX0FUVEFDS0VEX0xPU1RfQ0lU",
            "WRAFEiMKH1VOSU9OX0xPR19NRU1CRVJfQVRUQUNLRURfTUNJVFkQBhIkCiBV",
            "TklPTl9MT0dfTUVNQkVSX0FUVEFDS0VEX0ZBTExFThAHKlEKFFVOSU9OX0xP",
            "R19GSUdIVF9UWVBFEhoKFlVOSU9OX0xPR19GSUdIVF9BVFRBQ0sQABIdChlV",
            "TklPTl9MT0dfRklHSFRfTE9TVF9DSVRZEAEqNwoXVU5JT05fTE9HX1JFTEFU",
            "SU9OX1RZUEUSHAoYVU5JT05fTE9HX1JFTEFUSU9OX1NFVFVQEAAqXgoTVU5J",
            "T05fRElTVEFOQ0VfVFlQRRIXChNVTklPTl9ESVNUQU5DRV9ORUFSEAASFgoS",
            "VU5JT05fRElTVEFOQ0VfTUlEEAESFgoSVU5JT05fRElTVEFOQ0VfRkFSEAIq",
            "PQoNQ09ORkxJQ1RfVFlQRRIVChFDT05GTElDVF9UWVBFX1BWUBAAEhUKEUNP",
            "TkZMSUNUX1RZUEVfUFZFEAEqnwIKDUJBVFRMRV9SRVNVTFQSGAoUQkFUVExF",
            "X1JFU1VMVF9BVEtXSU4QABIYChRCQVRUTEVfUkVTVUxUX0RFRldJThABEhYK",
            "EkJBVFRMRV9SRVNVTFRfRFJBVxACEhsKF0JBVFRMRV9SRVNVTFRfQk9USF9E",
            "RUFEEAMSGgoWQkFUVExFX1JFU1VMVF9OT19GSUdIVBAEEhkKFUJBVFRMRV9S",
            "RVNVTFRfUFJPVEVDVBAFEhsKF0JBVFRMRV9SRVNVTFRfTk9fTkVBUkJZEAYS",
            "FwoTQkFUVExFX1JFU1VMVF9HVUFSRBAHEhsKF0JBVFRMRV9SRVNVTFRfRVhD",
            "RVBUSU9OEAkSGwoXQkFUVExFX1JFU1VMVF9USUxFX0ZVTEwQCiosChFCQVRU",
            "TEVfQVdBUkRfVFlQRRIXChNCQVRUTEVfQVdBUkRfU1VQUExZEAAqRwoKT1dO",
            "RVJfVFlQRRIcChhPQ0NVUFlfT1dORVJfVFlQRV9QTEFZRVIQABIbChdPQ0NV",
            "UFlfT1dORVJfVFlQRV9VTklPThABKoIBCgxEUklMTF9JRF9ERUYSEwoPRFJJ",
            "TExfTk9fU0VMRUNUEAASFgoSRFJJTExfVFVUT1JJQUxfTUlOEAESFwoSRFJJ",
            "TExfVFVUT1JJQUxfTUFYEOgHEhUKEERSSUxMX05PUk1BTF9NSU4Q6QcSFQoQ",
            "RFJJTExfTk9STUFMX01BWBDQDypmChREUklMTF9DT05ESVRJT05fVFlQRRIW",
            "ChJEUklMTF9DT05ESVRJT05fTk8QABIbChdEUklMTF9DT05ESVRJT05fTUlT",
            "U0lPThABEhkKFURSSUxMX0NPTkRJVElPTl9XT1JMRBACKm8KFERSSUxMX1RJ",
            "TEVfQVRUUklCVVRFEhUKEURSSUxMX1RJTEVfTk9STUFMEAASFAoQRFJJTExf",
            "VElMRV9TVEFSVBABEhIKDkRSSUxMX1RJTEVfRU5EEAISFgoSRFJJTExfVElM",
            "RV9EVVJBQkxFEGQqagoKRVBJQ19TVEFURRIUChBFUElDX1NUQVRFU19JTklU",
            "EAASFQoRRVBJQ19TVEFURVNfU1RBUlQQARIYChRFUElDX1NUQVRFU19DT01Q",
            "TEVURRACEhUKEUVQSUNfU1RBVEVTX0FXQVJEEAMqbwoRRVBJQ19QTEFZRVJf",
            "U1RBVEUSGwoXRVBJQ19QTEFZRVJfU1RBVEVTX05PTkUQABIdChlFUElDX1BM",
            "QVlFUl9TVEFURVNfRVhQSVJFEAESHgoaRVBJQ19QTEFZRVJfU1RBVEVTX0FX",
            "QVJERUQQAio3CgpTUlZfU1RBVFVTEhMKD1NSVl9TVEFUVVNfT1BFThAAEhQK",
            "EFNSVl9TVEFUVVNfQ0xPU0UQASrSAwoNSEVST19BUk1fVFlQRRIRCg1IRVJP",
            "X0FSTV9OT05FEAASFQoRSEVST19BUk1fSU5GQU5UUlkQChIbChdIRVJPX0FS",
            "TV9IRUFWWV9JTkZBTlRSWRALEhsKF0hFUk9fQVJNX0dVQVJEX0lORkFOVFJZ",
            "EAwSGwoXSEVST19BUk1fU1BFQVJfSU5GQU5UUlkQDRIcChhIRVJPX0FSTV9T",
            "QVZBR0VfSU5GQU5UUlkQDhIcChhIRVJPX0FSTV9SQVRUQU5fSU5GQU5UUlkQ",
            "DxIUChBIRVJPX0FSTV9DQVZBTFJZEBQSGgoWSEVST19BUk1fTElHSFRfQ0FW",
            "QUxSWRAVEhoKFkhFUk9fQVJNX0hFQVZZX0NBVkFMUlkQFhIZChVIRVJPX0FS",
            "TV9JUk9OX0NBVkFMUlkQFxIYChRIRVJPX0FSTV9CT1dfQ0FWQUxSWRAYEh0K",
            "GUhFUk9fQVJNX0VMRVBIQU5UX0NBVkFMUlkQGRITCg9IRVJPX0FSTV9CT1dN",
            "RU4QHhIYChRIRVJPX0FSTV9ERUFEX0JPV01FThAfEhgKFEhFUk9fQVJNX0xP",
            "TkdfQk9XTUVOECASGQoVSEVST19BUk1fQ1JPU1NfQk9XTUVOECFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cspb.ERR_CODE), typeof(global::Cspb.ENTITY_TYPE), typeof(global::Cspb.CITY_TYPE), typeof(global::Cspb.CITY_STATE), typeof(global::Cspb.TROOP_STATE), typeof(global::Cspb.TILE_ACTION_TYPE), typeof(global::Cspb.ITEM_TYPE), typeof(global::Cspb.RESOURCE_ID), typeof(global::Cspb.MC_TYPE), typeof(global::Cspb.REFRESH_TYPE), typeof(global::Cspb.CHAT_STATUS), typeof(global::Cspb.LOGIN_ACTION), typeof(global::Cspb.UNION_TITLE_TYPE), typeof(global::Cspb.UNION_OP_TYPE), typeof(global::Cspb.UNION_JOIN_LIMIT), typeof(global::Cspb.UNION_RELATION_TYPE), typeof(global::Cspb.UNION_LOG_TYPE), typeof(global::Cspb.UNION_LOG_EVENT_TYPE), typeof(global::Cspb.UNION_LOG_MEMBER_TYPE), typeof(global::Cspb.UNION_LOG_FIGHT_TYPE), typeof(global::Cspb.UNION_LOG_RELATION_TYPE), typeof(global::Cspb.UNION_DISTANCE_TYPE), typeof(global::Cspb.CONFLICT_TYPE), typeof(global::Cspb.BATTLE_RESULT), typeof(global::Cspb.BATTLE_AWARD_TYPE), typeof(global::Cspb.OWNER_TYPE), typeof(global::Cspb.DRILL_ID_DEF), typeof(global::Cspb.DRILL_CONDITION_TYPE), typeof(global::Cspb.DRILL_TILE_ATTRIBUTE), typeof(global::Cspb.EPIC_STATE), typeof(global::Cspb.EPIC_PLAYER_STATE), typeof(global::Cspb.SRV_STATUS), typeof(global::Cspb.HERO_ARM_TYPE), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 通用消息错误码
  /// </summary>
  public enum ERR_CODE {
    [pbr::OriginalName("ERR_CODE_NO_ERROR")] NoError = 0,
    /// <summary>
    /// 通用错误     1-100
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INTERNAL_ERR")] InternalErr = 1,
    [pbr::OriginalName("ERR_CODE_PF_ERR")] PfErr = 2,
    [pbr::OriginalName("ERR_CODE_ERR_SERVER_DATE")] ErrServerDate = 3,
    [pbr::OriginalName("ERR_CODE_PF_INVALID_ACCESS_TOKEN")] PfInvalidAccessToken = 4,
    [pbr::OriginalName("ERR_CODE_PERMISSION_VERIFY_FAILED")] PermissionVerifyFailed = 5,
    [pbr::OriginalName("ERR_CODE_ERR_ILLEGAL_REQ")] ErrIllegalReq = 6,
    /// <summary>
    /// 玩家操作的实体不属于玩家(玩家请求别的玩家的数据进行操作)
    /// </summary>
    [pbr::OriginalName("ERR_CODE_OP_ET_NOT_BELONG_TO_YOUR")] OpEtNotBelongToYour = 7,
    [pbr::OriginalName("ERR_CODE_PF_CHARACTER_CREATE_FAILED")] PfCharacterCreateFailed = 8,
    [pbr::OriginalName("ERR_CODE_PF_LOGIN_FAILED")] PfLoginFailed = 9,
    /// <summary>
    /// 要绑定的账号有角色
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PF_ACC_LINK_HASCHAR")] PfAccLinkHaschar = 10,
    /// <summary>
    /// 要绑定的账号失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PF_ACC_LINK_FAUKED")] PfAccLinkFauked = 11,
    /// <summary>
    /// 错误的账号类型
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PF_ACC_INVALIDACCOUNTTYPE")] PfAccInvalidaccounttype = 12,
    /// <summary>
    /// 帐号&amp;登录相关 100 - 1000
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NOT_FOUND")] PlayerNotFound = 101,
    /// <summary>
    /// 玩家名已存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NAME_ALREADY_EXIST")] PlayerNameAlreadyExist = 102,
    /// <summary>
    /// 玩家名长度限制
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NAME_LEN_LIMIT")] PlayerNameLenLimit = 103,
    /// <summary>
    /// 玩家名包含敏感词
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NAME_BAD_WORD")] PlayerNameBadWord = 104,
    /// <summary>
    /// 玩家Auth失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_AUTH_FAILED")] AuthFailed = 105,
    /// <summary>
    /// 网关账号创建失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ACCOUNT_CREATE_FAILED")] AccountCreateFailed = 106,
    /// <summary>
    /// 网关上玩家不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NOT_FOUND_2")] PlayerNotFound2 = 107,
    /// <summary>
    /// 网关上账号不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ACCOUNT_NOT_FOUND")] AccountNotFound = 108,
    /// <summary>
    /// 网关上增加玩家失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_GATE_ADD_ROLE_FAILED")] GateAddRoleFailed = 109,
    /// <summary>
    /// 设备UDID错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_DEVICE")] InvalidDevice = 110,
    /// <summary>
    /// 只能绑定匿名账号
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CANOT_BIND")] CanotBind = 111,
    /// <summary>
    /// 该服务器已存在角色
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DUPLICATE_CREATE_PLAYER")] DuplicateCreatePlayer = 112,
    /// <summary>
    /// 多点登录，等待已有角色登出超时
    /// </summary>
    [pbr::OriginalName("ERR_CODE_LOGIN_WAIT_LOGOUT_TIMEOUT")] LoginWaitLogoutTimeout = 113,
    /// <summary>
    /// 多点登录， 已有登录状态错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_LOGIN_WITH_ERR_STATE")] LoginWithErrState = 114,
    /// <summary>
    /// clientinfo 为空
    /// </summary>
    [pbr::OriginalName("ERR_CODE_NILCLIENTINFO")] Nilclientinfo = 115,
    /// <summary>
    /// 目标服务器没找到
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SERVER_NOT_FOUND")] ServerNotFound = 116,
    /// <summary>
    /// 连接目标服务器失败
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONNECT_SERVER_FAILED")] ConnectServerFailed = 117,
    /// <summary>
    /// 多次登陆
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DUPLICATE_LOGIN")] DuplicateLogin = 118,
    /// <summary>
    /// FastLoginSecret错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FASTLOGINSECRETERR")] Fastloginsecreterr = 119,
    /// <summary>
    /// 被禁止消息
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FORBIDEDMSG")] Forbidedmsg = 120,
    /// <summary>
    /// 名字无改变
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYERNAME_NOCHANG")] PlayernameNochang = 121,
    /// <summary>
    /// 名字无改变
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NAME_LEN_SHORT")] PlayerNameLenShort = 122,
    /// <summary>
    /// play相关 1000 - 2000 city/hero/skill/breport/land
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_CITY_ID")] ErrCityId = 1001,
    /// <summary>
    /// 没有找到英雄
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_HERO_RID")] ErrHeroRid = 1002,
    /// <summary>
    /// 英雄在其他队伍中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_IS_IN_OTHER_TROOP")] HeroIsInOtherTroop = 1003,
    /// <summary>
    /// 玩家资源不够
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_RES_LACK")] PlayerResLack = 1004,
    /// <summary>
    /// 没有找到建筑
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_BUILD_ID")] ErrBuildId = 1005,
    /// <summary>
    /// 城建已经达到满级
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_ALREADY_MAX_LEVEL")] BuildAlreadyMaxLevel = 1006,
    /// <summary>
    /// 需要升级其他依赖建筑
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_BUILD_RELY_ON")] ErrBuildRelyOn = 1007,
    /// <summary>
    /// 建筑已经升级
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_ALREADY_UPGRADE")] BuildAlreadyUpgrade = 1008,
    /// <summary>
    /// 战报已拉取
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BREPORT_ALREADY_COLLECT")] BreportAlreadyCollect = 1009,
    /// <summary>
    /// 拉取战报数量已达最大
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FULL_COLLECT_BREPORT")] FullCollectBreport = 1010,
    /// <summary>
    /// 技能已经被研究
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SKILL_ALREADY_RESEARCH")] SkillAlreadyResearch = 1012,
    /// <summary>
    /// 技能研究完成
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SKILL_IS_INTEGRITY")] SkillIsIntegrity = 1013,
    /// <summary>
    /// 第一个技能英雄等级不够，第一个技能英雄没有觉醒
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_CANNOT_LEARN_SKILL")] HeroCannotLearnSkill = 1014,
    /// <summary>
    /// 英雄没有学习技能, 因此不能遗忘
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_CANNOT_FORGET_SKILL")] HeroCannotForgetSkill = 1015,
    /// <summary>
    /// 没有找到战报
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_BREPORT_ID")] ErrBreportId = 1016,
    /// <summary>
    /// 英雄缺少足够的可分配属性点
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_HERO_REMAIN_ASGN_LACK")] ErrHeroRemainAsgnLack = 1017,
    /// <summary>
    /// 英雄红星已经满了，无法进阶
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ALREADY_MAX_ADVSTAR")] HeroAlreadyMaxAdvstar = 1018,
    /// <summary>
    /// 指定的消耗英雄无法删除 (学习了技能,锁定, 在队伍中)
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONSUME_HERO_CANNOT_DEL")] ConsumeHeroCannotDel = 1019,
    /// <summary>
    /// 进阶消耗的英雄与进阶英雄hero_id的不同
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PROMOTE_CONSUME_HERO_NOT_SAME")] PromoteConsumeHeroNotSame = 1020,
    /// <summary>
    /// 英雄已经觉醒
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_HAS_AWAKE")] HeroHasAwake = 1022,
    /// <summary>
    /// 玩家已完成新手教学
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_ALREADY_FINISH_NEWBIE")] PlayerAlreadyFinishNewbie = 1024,
    /// <summary>
    /// 觉醒英雄和消耗英雄星级不一样
    /// </summary>
    [pbr::OriginalName("ERR_CODE_AWAKE_CONSUME_STAR_NOT_SAME")] AwakeConsumeStarNotSame = 1025,
    /// <summary>
    /// 被消耗的英雄在队伍中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONSUME_HERO_IN_TROOP")] ConsumeHeroInTroop = 1026,
    /// <summary>
    /// 觉醒英雄消耗个数错误（小于2）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HREO_AWAKE_CONSUME_CNT_ERR")] HreoAwakeConsumeCntErr = 1027,
    /// <summary>
    /// 英雄技能索引不在 0-2 之间
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SKILL_INDEX_OUT_OF_RANGE")] SkillIndexOutOfRange = 1029,
    /// <summary>
    /// 技能不能被学习(研究进度小于100，已经超过最大学习次数)
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SKILL_CANNOT_BE_LEARNED")] SkillCannotBeLearned = 1030,
    /// <summary>
    /// 英雄index位置已经学习了技能
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INDEX_ALREADY_LEARN_SKILL")] IndexAlreadyLearnSkill = 1031,
    /// <summary>
    /// 发送的id里面有重复
    /// </summary>
    [pbr::OriginalName("ERR_CODE_REPEAT_ID")] RepeatId = 1032,
    /// <summary>
    /// 英雄已经学习了该技能,不能再次该学习
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ALREADY_LEARN_THIS_SKILL")] HeroAlreadyLearnThisSkill = 1033,
    /// <summary>
    /// 没有找到此技能
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_SKILL_ID")] ErrSkillId = 1034,
    /// <summary>
    /// 英雄兵种与技能可学习兵种不符
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_KIND_NOT_MATCH_SKILL")] HeroKindNotMatchSkill = 1035,
    /// <summary>
    /// 英雄不能研究这个技能 (英雄兵种, 星级不符)
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_CONNOT_RESEARCH_THIS_SKILL")] HeroConnotResearchThisSkill = 1036,
    /// <summary>
    /// 技能等级不一致(在学习技能时为了避免数据不一致,需要与客户端验证技能等级)
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_SKILL_LEVEL")] ErrSkillLevel = 1037,
    /// <summary>
    /// 战法经验不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_SKILL_EXP_LACK")] ErrSkillExpLack = 1038,
    /// <summary>
    /// 英雄已锁定
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ALREADY_LOCKED")] HeroAlreadyLocked = 1039,
    /// <summary>
    /// 英雄已解锁
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ALREADY_UNLOCKED")] HeroAlreadyUnlocked = 1040,
    /// <summary>
    /// 属性分配的值错误（小于0或者比原来的值小）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ALLOT_ASGN_VALUE_ERR")] AllotAsgnValueErr = 1041,
    /// <summary>
    /// 英雄等级不能觉醒
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_LEVEL_CANNOT_AWAKE")] HeroLevelCannotAwake = 1042,
    /// <summary>
    /// 英雄自带技能等级不能觉醒
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIRST_SKILL_LEVEL_CANNOT_AWAKE")] FirstSkillLevelCannotAwake = 1043,
    /// <summary>
    /// 玩家钻石不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_DIAMOND_LACK")] PlayerDiamondLack = 1044,
    /// <summary>
    /// is_free 字段不一致
    /// </summary>
    [pbr::OriginalName("ERR_CODE_RESET_ASGN_TYPE_NOT_MATCH")] ResetAsgnTypeNotMatch = 1045,
    /// <summary>
    /// 建筑没有在升级
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_IS_NOT_UPGRADE")] BuildIsNotUpgrade = 1046,
    /// <summary>
    /// 收税次数已达上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_COLLECT_TAXES_CNT_MAX")] CollectTaxesCntMax = 1047,
    /// <summary>
    /// 资源交易目标与源资源一样
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRANS_RES_SRC_DEST_SAME")] TransResSrcDestSame = 1048,
    /// <summary>
    /// 资源交易小于0
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRANS_RES_CNT_LESS_THAN_0")] TransResCntLessThan0 = 1049,
    /// <summary>
    /// 玩家没有建筑交易所,不能交易
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_HAVE_NOT_TRANS_BUILD")] PlayerHaveNotTransBuild = 1050,
    /// <summary>
    /// src/dest 不能交易
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRANS_RES_SRC_DEST_ERR")] TransResSrcDestErr = 1051,
    /// <summary>
    /// 玩家收藏土地已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FULL_COLLECT_LANDS")] FullCollectLands = 1052,
    /// <summary>
    /// 玩家金币不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_PLAYER_COIN_LACK")] ErrPlayerCoinLack = 1053,
    /// <summary>
    /// 玩家英雄上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_HERO_FULL")] PlayerHeroFull = 1054,
    /// <summary>
    /// 玩家技能上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_SKILL_FULL")] PlayerSkillFull = 1055,
    /// <summary>
    /// 任务不处于可领奖状态
    /// </summary>
    [pbr::OriginalName("ERR_CODE_NOT_COMPLEATED_TASK")] NotCompleatedTask = 1056,
    /// <summary>
    /// 不合法的任务id
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TASKID")] ErrTaskid = 1057,
    /// <summary>
    /// 任务不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TASK_NOT_EXIST")] TaskNotExist = 1058,
    /// <summary>
    /// 后续任务ID不合法
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_NEXT_TASKID")] ErrNextTaskid = 1059,
    /// <summary>
    /// 未知的任务奖励名称
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNKNOWN_TASK_PRIZE")] UnknownTaskPrize = 1060,
    /// <summary>
    /// 没有找到商品 如商品id错误 商品已经出售
    /// </summary>
    [pbr::OriginalName("ERR_CODE_NO_GOODS_NAME")] NoGoodsName = 1061,
    /// <summary>
    /// 购买商品时 缺少商品所需要的资源
    /// </summary>
    [pbr::OriginalName("ERR_CODE_LACK_RESOURCE")] LackResource = 1062,
    /// <summary>
    /// 无效的购买请求
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_PURCHASE")] InvalidPurchase = 1063,
    /// <summary>
    /// 市场ID错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_WRONG_MARKET_ID")] WrongMarketId = 1064,
    /// <summary>
    /// 市场未解锁
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MARKET_LOCKED")] MarketLocked = 1065,
    /// <summary>
    ///未满足收税时间间隔
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TAX_TIME_INTERVAL")] TaxTimeInterval = 1066,
    /// <summary>
    /// 已经卖出
    /// </summary>
    [pbr::OriginalName("ERR_CODE_GOODS_SOLD_OUT")] GoodsSoldOut = 1067,
    /// <summary>
    /// 交易 资源兑换率为0 没有启用交易功能时
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRADE_ZERO_RATE")] TradeZeroRate = 1068,
    /// <summary>
    /// 无效的资源 数量非正 id错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_RES")] InvalidRes = 1069,
    /// <summary>
    /// 同种资源无法交易
    /// </summary>
    [pbr::OriginalName("ERR_CODE_SAME_RES")] SameRes = 1070,
    /// <summary>
    /// 超过商店最大刷新次数
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MAX_MARKET_REFRESH_TIMES")] MaxMarketRefreshTimes = 1071,
    /// <summary>
    /// 升级建筑物所需的地块等级不够
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_TILE_LEVEL_LIMIT")] BuildTileLevelLimit = 1072,
    /// <summary>
    /// 进阶消耗英雄为0
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PROMOTE_CONSUME_HERO_CNT_ERR")] PromoteConsumeHeroCntErr = 1073,
    /// <summary>
    /// 人民币玩家收税次数已达上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FORCE_COLLECT_TAXES_CNT_MAX")] ForceCollectTaxesCntMax = 1074,
    /// <summary>
    /// 人民币玩家不需要强征，已经到第二天了
    /// </summary>
    [pbr::OriginalName("ERR_CODE_NOT_REQUIRE_FORCE_COLLECT")] NotRequireForceCollect = 1075,
    /// <summary>
    /// 政令不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ORDER_LACK")] OrderLack = 1076,
    /// <summary>
    /// 头像的index错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_AVATAR_WRONG_INDEX")] AvatarWrongIndex = 1077,
    /// <summary>
    /// 简介长度错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INTRO_WRONG_LENGTH")] IntroWrongLength = 1078,
    /// <summary>
    /// 简介带有敏感词
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INTRO_BAD_WORD")] IntroBadWord = 1079,
    /// <summary>
    /// push event错误, 服务器没有定义
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_PUSH_EVENT")] ErrPushEvent = 1080,
    /// <summary>
    ///gacha
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_GACHA_ERR_PACKAGEID")] ErrGachaErrPackageid = 1081,
    /// <summary>
    /// push event错误, 服务器没有定义
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_GACHA_END")] ErrGachaEnd = 1095,
    /// <summary>
    /// 客户端商店数据为过期
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MARKET_OLD_DATA")] MarketOldData = 1096,
    /// <summary>
    /// 联盟相关
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_OP_NO_AUTHORITY")] UnionOpNoAuthority = 1100,
    /// <summary>
    /// 联盟名已存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NAME_ALREADY_EXIST")] UnionNameAlreadyExist = 1101,
    /// <summary>
    /// 联盟名长度限制
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NAME_LEN_LIMIT")] UnionNameLenLimit = 1102,
    /// <summary>
    /// 联盟名包含敏感词
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NAME_BAD_WORD")] UnionNameBadWord = 1103,
    /// <summary>
    /// 联盟不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NOT_EXIST")] UnionNotExist = 1104,
    /// <summary>
    /// 玩家已经申请该联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_ALREADY_APPLY")] UnionAlreadyApply = 1105,
    /// <summary>
    /// 玩家没有申请该联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NOT_APPLY")] UnionNotApply = 1107,
    /// <summary>
    /// 玩家不在该联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MEMBER_NOT_EXIST")] UnionMemberNotExist = 1108,
    /// <summary>
    /// 该职位不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_TITLE_NOT_EXIST")] UnionTitleNotExist = 1109,
    /// <summary>
    /// 不能任命该成员
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_APPOINT")] UnionCannotAppoint = 1110,
    /// <summary>
    /// 不能移除该成员
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_REMOVE")] UnionCannotRemove = 1111,
    /// <summary>
    /// 不能禅让给该成员
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_DEMISE")] UnionCannotDemise = 1112,
    /// <summary>
    /// 玩家在退盟冷却中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_QUIT_COOLDOWN")] UnionQuitCooldown = 1113,
    /// <summary>
    /// 已达最大联盟申请数量
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_APPLY_MAX_NUM")] UnionApplyMaxNum = 1114,
    /// <summary>
    /// 联盟成员已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MEMBER_FULL")] UnionMemberFull = 1115,
    /// <summary>
    /// 不能申请或加入其他区域的联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_JOIN_WRONG_AREA")] UnionJoinWrongArea = 1116,
    /// <summary>
    /// 联盟申请或加入条件：禁止加入
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_JOIN_FORBID")] UnionJoinForbid = 1117,
    /// <summary>
    /// 玩家已经加入了联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_PLAYER_ALREADY_IN_UNION")] UnionPlayerAlreadyInUnion = 1118,
    /// <summary>
    /// 创建联盟时城主府等级不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CREATE_MAIN_CITY_LIMIT")] UnionCreateMainCityLimit = 1119,
    /// <summary>
    /// 创建联盟时金币不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CREATE_RES_COIN_LIMIT")] UnionCreateResCoinLimit = 1120,
    /// <summary>
    /// 联盟该职位已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_TITLE_NUM_FULL")] UnionTitleNumFull = 1121,
    /// <summary>
    /// 需要申请加入
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NEED_APPLY")] UnionNeedApply = 1122,
    /// <summary>
    /// 不能直接加入
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_JOIN")] UnionCannotJoin = 1123,
    /// <summary>
    /// 设置了错误的联盟加入条件
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_WRONG_JOIN_LIMIT")] UnionWrongJoinLimit = 1124,
    /// <summary>
    /// 不能捐献
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_DONATE")] UnionCannotDonate = 1125,
    /// <summary>
    /// 设置了错误的联盟关系
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_WRONG_RELATION")] UnionWrongRelation = 1126,
    /// <summary>
    /// 联盟外交关系已达上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_RELATION_NUM_FULL")] UnionRelationNumFull = 1127,
    /// <summary>
    /// 联盟外交关系不能改变
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_RELATION_CANNOT_CHANGE")] UnionRelationCannotChange = 1128,
    /// <summary>
    /// 联盟标记数量已达上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MARK_NUM_FULL")] UnionMarkNumFull = 1129,
    /// <summary>
    /// 联盟标记名长度限制
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MARK_NAME_LEN_LIMIT")] UnionMarkNameLenLimit = 1130,
    /// <summary>
    /// 联盟标记内容长度限制
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MARK_CONTENt_LEN_LIMIT")] UnionMarkContentLenLimit = 1131,
    /// <summary>
    /// 联盟标记包含敏感词
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_MARK_BAD_WORD")] UnionMarkBadWord = 1132,
    /// <summary>
    /// 联盟描述长度限制
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_DESC_LEN_LIMIT")] UnionDescLenLimit = 1133,
    /// <summary>
    /// 联盟描述包含敏感词
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_DESC_BAD_WORD")] UnionDescBadWord = 1134,
    /// <summary>
    /// 没有发起禅让
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_NO_DEMISE")] UnionNoDemise = 1135,
    /// <summary>
    /// 不能交换两个官员的职位
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_SWAP_TITLE")] UnionCannotSwapTitle = 1136,
    /// <summary>
    /// 不能解散联盟
    /// </summary>
    [pbr::OriginalName("ERR_CODE_UNION_CANNOT_DISSOLVE")] UnionCannotDissolve = 1137,
    /// <summary>
    /// 沦陷相关
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FALLEN_NOT_FALLEN")] FallenNotFallen = 1140,
    /// <summary>
    /// 不能上缴反叛资源
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FALLEN_CANNOT_PAY_REVOLT_RES")] FallenCannotPayRevoltRes = 1141,
    /// <summary>
    /// 演武 1150 ~ 1200
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_ID_NOT_EXIST")] DrillIdNotExist = 1150,
    /// <summary>
    /// 关卡没有开启
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_ID_IS_NOT_OPEN")] DrillIdIsNotOpen = 1151,
    /// <summary>
    /// 关卡已经打开
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_ID_IS_ALREADY_OPEN")] DrillIdIsAlreadyOpen = 1152,
    /// <summary>
    /// 关卡不能打开（前置条件不满足）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_NO_MEET_CONDITION")] DrillNoMeetCondition = 1153,
    /// <summary>
    /// 不能攻击关卡土地（没有连接地）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_CANT_ATTACK_TILE")] DrillCantAttackTile = 1154,
    /// <summary>
    /// 土地已经被占领
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_TILE_IS_ALREADY_OCCUPY")] DrillTileIsAlreadyOccupy = 1155,
    /// <summary>
    /// 土地位置错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_INVALID_TILE_POS")] DrillInvalidTilePos = 1156,
    /// <summary>
    /// 攻击部队英雄数量错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_HEROS_WRONG_NUMBER")] DrillHerosWrongNumber = 1157,
    /// <summary>
    /// 攻击部队英雄不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_HERO_NOT_EXIST")] DrillHeroNotExist = 1158,
    /// <summary>
    /// 攻击部队配置不满足土地要求（英雄数量，Cost）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_HEROS_NOT_REACH_TILE")] DrillHerosNotReachTile = 1159,
    /// <summary>
    /// 金币不够
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_NO_ENOUGH_COIN")] DrillNoEnoughCoin = 1160,
    /// <summary>
    /// 当前关卡每通过，不能开启下一关（教学演武有效）
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_NO_PASS")] DrillNoPass = 1161,
    /// <summary>
    /// 关卡处于冷却期，不能开启下一关
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_IN_CD")] DrillInCd = 1162,
    /// <summary>
    /// 前一难度没有通关，不能开启当前难度关卡
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_TOO_DIFFICULTY")] DrillTooDifficulty = 1163,
    /// <summary>
    /// 教学演武不能跳过动画学演武有效）    
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_TUTORIAL_CANT_SKIP")] DrillTutorialCantSkip = 1164,
    /// <summary>
    /// 教学演武没有统计数据
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_TUTORIAL_NO_STATISTIC")] DrillTutorialNoStatistic = 1165,
    /// <summary>
    /// 演武攻击部队，武将重复
    /// </summary>
    [pbr::OriginalName("ERR_CODE_DRILL_DUPLICATE_HERO")] DrillDuplicateHero = 1166,
    /// <summary>
    /// 建造队列已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_QUEUE_FULL")] BuildQueueFull = 1200,
    /// <summary>
    /// 登录天数奖励
    /// </summary>
    [pbr::OriginalName("ERR_CODE_LOGIN_DAY")] LoginDay = 1201,
    /// <summary>
    /// 任务ID错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TASK_ID")] ErrTaskId = 1202,
    /// <summary>
    /// 任务已经完成
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TASK_ALREADY_COMPLETE")] ErrTaskAlreadyComplete = 1203,
    /// <summary>
    /// 任务已经领奖
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TASK_ALREADY_AWARD")] ErrTaskAlreadyAward = 1204,
    /// <summary>
    /// 登录超过30天
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_LOGIN_EVENT_MORE")] ErrLoginEventMore = 1205,
    /// <summary>
    /// 当天奖励已领取
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_LOGIN_EVENT_AWARD")] ErrLoginEventAward = 1206,
    /// <summary>
    /// 邮件 1210 - 1219
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MAIL_NOT_IN_UNION")] MailNotInUnion = 1210,
    /// <summary>
    /// map相关 2000 - 3000 troop/march/fighter/tile
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ALLOC_MAP_POS_FAILED")] AllocMapPosFailed = 2001,
    /// <summary>
    /// 玩家不是土地所有者
    /// </summary>
    [pbr::OriginalName("ERR_CODE_NOT_TILE_OWNER")] NotTileOwner = 2002,
    /// <summary>
    /// 土地在占免期
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TILE_ON_PROTECT")] TileOnProtect = 2003,
    /// <summary>
    /// 土地在放弃过程中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TILE_IS_GIVING_UP")] TileIsGivingUp = 2004,
    /// <summary>
    /// 土地位置错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_POS")] InvalidPos = 2005,
    /// <summary>
    /// 土地不在放弃过程中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TILE_NOT_GIVING_UP")] TileNotGivingUp = 2006,
    /// <summary>
    /// 土地所在格子位置错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_INVALID_GRID_POS")] InvalidGridPos = 2007,
    /// <summary>
    /// 拉取土地的格子过多
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TOO_MUCH_GRIDS")] TooMuchGrids = 2008,
    /// <summary>
    /// 行军请求类型错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MARCH_REQ_TYPE_ERR")] MarchReqTypeErr = 2009,
    /// <summary>
    /// 出征没有连通地块
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ATTACK_NO_NEARBY_TILE")] AttackNoNearbyTile = 2010,
    /// <summary>
    /// 地块不能被攻击
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TILE_CANNOT_ATTACK")] TileCannotAttack = 2011,
    /// <summary>
    /// 玩家不是地块所有者
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NOT_TILE_OWNER")] PlayerNotTileOwner = 2012,
    /// <summary>
    /// 没有此ID队伍
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TROOP_ID")] ErrTroopId = 2013,
    /// <summary>
    /// 英雄不在部队中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ISNOT_IN_TROOP")] HeroIsnotInTroop = 2014,
    /// <summary>
    /// 队伍中英雄数量达到上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIGHTER_NUM_LIMITED")] FighterNumLimited = 2015,
    /// <summary>
    /// 部队配置正在征兵的fighter
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOP_CTL_CONSCRIPT_FIGHTER")] TroopCtlConscriptFighter = 2016,
    /// <summary>
    /// 没有找到此ID的行军
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_MARCH_ID")] ErrMarchId = 2017,
    /// <summary>
    /// 已超过可撤回时间
    /// </summary>
    [pbr::OriginalName("ERR_CODE_RETURN_MARCH_ERR_TIME")] ReturnMarchErrTime = 2018,
    /// <summary>
    /// 部队数量错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TROOP_NO")] ErrTroopNo = 2019,
    /// <summary>
    /// 部队没有找到
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOP_NOT_FOUND")] TroopNotFound = 2020,
    /// <summary>
    /// 部队状态错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_TROOP_STATE")] ErrTroopState = 2021,
    /// <summary>
    /// 部队成员重伤
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIGHTER_SERIOUS_HURT")] FighterSeriousHurt = 2022,
    /// <summary>
    /// 部队成员位置错误
    /// </summary>
    [pbr::OriginalName("ERR_CODE_ERR_FIGHTER_POS")] ErrFighterPos = 2023,
    /// <summary>
    /// 2支部队不在同一城中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOPS_IN_TWO_CITIES")] TroopsInTwoCities = 2024,
    /// <summary>
    /// 征兵队列已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FULL_CONSCRIPT_QUEUE")] FullConscriptQueue = 2025,
    /// <summary>
    /// 体力不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_HERO_ENERGY_LACK")] HeroEnergyLack = 2026,
    /// <summary>
    /// 部队无法撤退
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOP_CANNOT_RETURN")] TroopCannotReturn = 2027,
    /// <summary>
    /// 部队不在城中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOP_IS_NOT_IN_CITY")] TroopIsNotInCity = 2028,
    /// <summary>
    /// 练兵次数
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRAIN_CNT_ERR")] TrainCntErr = 2029,
    /// <summary>
    /// 预备兵不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CITY_REDIF_LACK")] CityRedifLack = 2030,
    /// <summary>
    /// cnt &lt;= 0
    /// </summary>
    [pbr::OriginalName("ERR_CODE_REDIF_CONSCRIPT_REQ_CNT_ERR")] RedifConscriptReqCntErr = 2031,
    /// <summary>
    /// 城池cost不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CITY_COST_LACK")] CityCostLack = 2032,
    /// <summary>
    /// 征兵数量超过部队上限
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIGHTER_HP_MORE_THAN_MAX")] FighterHpMoreThanMax = 2033,
    /// <summary>
    /// normal &lt; 0 || redif &lt; 0
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONSCRIPT_REQ_CNT_ERR")] ConscriptReqCntErr = 2034,
    /// <summary>
    /// 英雄没有在征兵
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIGHTER_IS_NOT_CONSCRIPT")] FighterIsNotConscript = 2035,
    /// <summary>
    /// 返回部队请求部队转态与部队不一致
    /// </summary>
    [pbr::OriginalName("ERR_CODE_RETURN_TROOP_REQ_STATE_ERR")] ReturnTroopReqStateErr = 2036,
    /// <summary>
    /// 所有部队不能上阵相同的英雄
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOPS_CONNOT_HAVE_SAME_HERO")] TroopsConnotHaveSameHero = 2037,
    /// <summary>
    /// 筛选土地半径过大
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FILTER_RADIUS_TOO_LARGE")] FilterRadiusTooLarge = 2038,
    /// <summary>
    /// 玩家不是城池的所有者
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PLAYER_NOT_CITY_OWNER")] PlayerNotCityOwner = 2039,
    /// <summary>
    /// 调动指定的城市队伍已满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRANSFER_CITY_TROOPS_FULL")] TransferCityTroopsFull = 2040,
    /// <summary>
    /// 调动指定的位置与部队现在的位置一致
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TRANSFER_POS_SAME_TROOP_POS")] TransferPosSameTroopPos = 2041,
    /// <summary>
    /// 指定位置不能修建城池
    /// </summary>
    [pbr::OriginalName("ERR_CODE_POS_CONNOT_BUILD_CITY")] PosConnotBuildCity = 2042,
    /// <summary>
    /// 指定的城池类型不能修建
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONNOT_BUILD_THIS_CITY_TYPE")] ConnotBuildThisCityType = 2043,
    /// <summary>
    /// 指定修建的城池以满
    /// </summary>
    [pbr::OriginalName("ERR_CODE_BUILD_CITY_FULL")] BuildCityFull = 2044,
    /// <summary>
    /// 屯田,练兵,扫荡指定的土地上面有建筑
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TILE_ETYPE_IS_NOT_NOTHING")] TileEtypeIsNotNothing = 2045,
    /// <summary>
    /// 不能拆除的建筑类型
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CONNOT_DISMANTLE_CITY_TYPE")] ConnotDismantleCityType = 2046,
    /// <summary>
    /// 建筑状态不能别拆除
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CITY_STATE_CONNOT_DISMANTLE")] CityStateConnotDismantle = 2047,
    /// <summary>
    /// 放弃土地上拥有特殊的实体, 主城, 分城, 自己的城区
    /// </summary>
    [pbr::OriginalName("ERR_CODE_GIVEUP_SP_ENTITY")] GiveupSpEntity = 2048,
    /// <summary>
    /// 英雄正在征兵，不能再次征兵
    /// </summary>
    [pbr::OriginalName("ERR_CODE_FIGHTER_ALREADY_CONSCRIPT")] FighterAlreadyConscript = 2049,
    /// <summary>
    /// 英雄在征兵, 不能出征
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MARCH_CONSCRIPT_FIGHTE")] MarchConscriptFighte = 2050,
    /// <summary>
    /// 部队从要塞1调动到要塞2, 想撤退, 但是要塞1已经满了
    /// </summary>
    [pbr::OriginalName("ERR_CODE_OLD_FORTRESS_FULL")] OldFortressFull = 2051,
    /// <summary>
    /// 部队从要塞1调动到要塞2, 想撤退, 但是要塞1不存在
    /// </summary>
    [pbr::OriginalName("ERR_CODE_OLD_FORTRESS_NOT_EXIST")] OldFortressNotExist = 2052,
    /// <summary>
    /// 部队必须配置大营才可出征
    /// </summary>
    [pbr::OriginalName("ERR_CODE_TROOP_NEED_FIRST_FIGHTER")] TroopNeedFirstFighter = 2053,
    /// <summary>
    /// 不能迁城到此地
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CANNOT_MOVE_CITY_HERE")] CannotMoveCityHere = 2054,
    /// <summary>
    /// 有正在升级的建筑
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MOVE_CITY_BUILD_QUEUE")] MoveCityBuildQueue = 2055,
    /// <summary>
    /// 有正在征兵的队伍
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MOVE_CITY_CONSCRIPT_QUEUE")] MoveCityConscriptQueue = 2056,
    /// <summary>
    /// 被沦陷
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MOVE_CITY_FALLEN")] MoveCityFallen = 2057,
    /// <summary>
    /// 处于拆除中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_MOVE_CITY_DISMANTLE")] MoveCityDismantle = 2058,
    /// <summary>
    /// 坚守中
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CITY_IN_INVINCIBLE")] CityInInvincible = 2059,
    /// <summary>
    /// 状态不是normal，不能坚守
    /// </summary>
    [pbr::OriginalName("ERR_CODE_CITY_INVINCIBLE_STATE")] CityInvincibleState = 2060,
    /// <summary>
    /// 天下大势不能领奖
    /// </summary>
    [pbr::OriginalName("ERR_CODE_EPIC_CANNOT_AWARD")] EpicCannotAward = 2061,
    /// <summary>
    /// 玩家天下大势不能领奖
    /// </summary>
    [pbr::OriginalName("ERR_CODE_EPIC_PLAYER_CANNOT_AWARD")] EpicPlayerCannotAward = 2062,
    /// <summary>
    /// 声望不足
    /// </summary>
    [pbr::OriginalName("ERR_CODE_PRESTIGE_NOT_ENOUGH")] PrestigeNotEnough = 2063,
  }

  /// <summary>
  /// 为了保证实体的type唯一, 这里定义已经存在的实体类型, 需要与 iproto/type_def.go保持一致
  /// 主城: 1
  /// 玩家城区: 2
  /// 分城: 3
  /// 玩家要塞: 4
  /// 废墟: 5
  /// 野外要塞: 6
  /// npc城池: 7
  /// 玩家: 8, 服务器使用
  /// 联盟: 9, 服务器使用
  /// npc城区: 10, 服务器使用
  /// </summary>
  public enum ENTITY_TYPE {
    /// <summary>
    /// 土地
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NOTHING")] Nothing = 0,
    /// <summary>
    /// 主城中心
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_MAIN_CITY")] MainCity = 1,
    /// <summary>
    /// 主城/分城城区
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_CITY_DST")] CityDst = 2,
    /// <summary>
    /// 分城中心
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_CITY_SUB")] CitySub = 3,
    /// <summary>
    /// 玩家要塞
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_PFORTRESS")] Pfortress = 4,
    /// <summary>
    /// 废墟
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_RUINS")] Ruins = 5,
    /// <summary>
    /// 野外要塞
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NFORTRESS")] Nfortress = 6,
    /// <summary>
    /// npc城池
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NPC_CITY")] NpcCity = 7,
    /// <summary>
    /// npc城池
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NPC_CITY_DST")] NpcCityDst = 10,
    /// <summary>
    /// 地形，不能走到的地块
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_TERRIAN")] Terrian = 11,
    /// <summary>
    /// npc关卡
    /// </summary>
    [pbr::OriginalName("ENTITY_TYPE_NPC_GATE")] NpcGate = 12,
  }

  /// <summary>
  /// CITY_TYPE 是 ENTITY_TYPE 的子集, 这里在协议里面显示区分出来
  /// CITY_TYPE 与对应的 ENTITY_TYPE 值必须定义一样
  /// </summary>
  public enum CITY_TYPE {
    /// <summary>
    /// err 不应该存在
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_ERR")] Err = 0,
    /// <summary>
    /// 主城
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_MAINCITY")] Maincity = 1,
    /// <summary>
    /// 分城
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_SUBCITY")] Subcity = 3,
    /// <summary>
    /// 玩家要塞
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_PFORTRESS")] Pfortress = 4,
    /// <summary>
    /// 废墟
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_RUINS")] Ruins = 5,
    /// <summary>
    /// 野外要塞
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_NFORTRESS")] Nfortress = 6,
    /// <summary>
    /// npc城池
    /// </summary>
    [pbr::OriginalName("CITY_TYPE_NPCCITY")] Npccity = 7,
  }

  public enum CITY_STATE {
    /// <summary>
    /// 修建中
    /// </summary>
    [pbr::OriginalName("CITY_STATE_BUILD")] Build = 0,
    /// <summary>
    /// 正常
    /// </summary>
    [pbr::OriginalName("CITY_STATE_NORMAL")] Normal = 1,
    /// <summary>
    /// 拆除中
    /// </summary>
    [pbr::OriginalName("CITY_STATE_DISMANTLE")] Dismantle = 2,
    /// <summary>
    /// 坚守准备
    /// </summary>
    [pbr::OriginalName("CITY_STATE_INVINCIBLE_PREPARE")] InvinciblePrepare = 3,
    /// <summary>
    /// 坚守
    /// </summary>
    [pbr::OriginalName("CITY_STATE_INVINCIBLE")] Invincible = 4,
    /// <summary>
    /// 坚守CD
    /// </summary>
    [pbr::OriginalName("CITY_STATE_INVINCIBLE_CD")] InvincibleCd = 5,
  }

  public enum TROOP_STATE {
    /// <summary>
    /// 在城池中
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_INCITY")] Incity = 0,
    /// <summary>
    /// 行军中
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_MARCH")] March = 1,
    /// <summary>
    /// 平局
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_DRAW_REST")] DrawRest = 2,
    /// <summary>
    /// 驻守
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_GARRISON")] Garrison = 3,
    /// <summary>
    /// 返回
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_RETURN")] Return = 4,
    /// <summary>
    /// 练兵
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_TRAIN")] Train = 5,
    /// <summary>
    /// 屯田
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_COLLECT")] Collect = 6,
    /// <summary>
    /// 调动
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_TRANSFER")] Transfer = 7,
    /// <summary>
    /// 战斗中（没有出战斗结果）
    /// </summary>
    [pbr::OriginalName("TROOP_STATE_INBATTLE")] Inbattle = 8,
  }

  public enum TILE_ACTION_TYPE {
    [pbr::OriginalName("TILE_ACTION_TYPE_ERR")] Err = 0,
    /// <summary>
    /// 出征
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_ATTACK")] Attack = 1,
    /// <summary>
    /// 驻守
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_GARRISON")] Garrison = 2,
    /// <summary>
    /// 扫荡
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_MOPPING")] Mopping = 3,
    /// <summary>
    /// 练兵
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_TRAIN")] Train = 4,
    /// <summary>
    /// 屯田
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_COLLECT")] Collect = 5,
    /// <summary>
    /// 平局
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_DRAW_REST")] DrawRest = 6,
    /// <summary>
    /// 调动部队
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_TRANSFER")] Transfer = 7,
    /// <summary>
    /// 撤退地块部队
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_RETREAT")] Retreat = 8,
    /// <summary>
    /// 撤退行军中的部队
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_RETREAT_ON_WAY")] RetreatOnWay = 9,
    /// <summary>
    /// 撤退调动部队
    /// </summary>
    [pbr::OriginalName("TILE_ACTION_TYPE_RETREAT_TRANSFER")] RetreatTransfer = 10,
  }

  /// <summary>
  /// 玩家能获得的物品类型
  /// </summary>
  public enum ITEM_TYPE {
    /// <summary>
    /// 错误, 用于表示错误
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_ERR")] Err = 0,
    /// <summary>
    /// 钻石
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_DIAMOND")] Diamond = 1,
    /// <summary>
    /// 钱币
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_COIN")] Coin = 2,
    /// <summary>
    /// 资源: 木材, 石料, 粮草, 铁矿, 政令, 名望
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_RESOURCE")] Resource = 3,
    /// <summary>
    /// 英雄
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_HERO")] Hero = 4,
    /// <summary>
    /// 技能
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_SKILL")] Skill = 5,
    /// <summary>
    ///ITEM_TYPE_HERO_EXP    = 6;  // 英雄经验未使用
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_SKILL_EXP")] SkillExp = 7,
    /// <summary>
    /// 技能研究度
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_SKILL_PRO")] SkillPro = 8,
    /// <summary>
    /// 卡包
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_GACHA_PKG")] GachaPkg = 9,
    /// <summary>
    /// 预备兵
    /// </summary>
    [pbr::OriginalName("ITEM_TYPE_REDIF")] Redif = 10,
  }

  /// <summary>
  /// 资源id定义
  /// </summary>
  public enum RESOURCE_ID {
    /// <summary>
    /// 错误, 不应该存在
    /// </summary>
    [pbr::OriginalName("RESOURCE_ERR")] ResourceErr = 0,
    /// <summary>
    /// 粮草
    /// </summary>
    [pbr::OriginalName("RESOURCE_FOOD")] ResourceFood = 1,
    /// <summary>
    /// 石料
    /// </summary>
    [pbr::OriginalName("RESOURCE_STONE")] ResourceStone = 2,
    /// <summary>
    /// 木材
    /// </summary>
    [pbr::OriginalName("RESOURCE_WOOD")] ResourceWood = 3,
    /// <summary>
    /// 铁矿
    /// </summary>
    [pbr::OriginalName("RESOURCE_STEEL")] ResourceSteel = 4,
    /// <summary>
    /// 名望
    /// </summary>
    [pbr::OriginalName("RESOURCE_PRESITGE")] ResourcePresitge = 5,
    /// <summary>
    /// 政令    
    /// </summary>
    [pbr::OriginalName("RESOURCE_ORDER")] ResourceOrder = 6,
  }

  /// <summary>
  /// 邮件和聊天的类型定义
  /// </summary>
  public enum MC_TYPE {
    /// <summary>
    /// 错误
    /// </summary>
    [pbr::OriginalName("MAIL_TYPE_NONE")] MailTypeNone = 0,
    /// <summary>
    /// 个人邮件
    /// </summary>
    [pbr::OriginalName("MAIL_TYPE_PLAYER")] MailTypePlayer = 1,
    /// <summary>
    /// 全服邮件
    /// </summary>
    [pbr::OriginalName("MAIL_TYPE_SERVER")] MailTypeServer = 2,
    /// <summary>
    /// 联盟邮件
    /// </summary>
    [pbr::OriginalName("MAIL_TYPE_UNION")] MailTypeUnion = 3,
    /// <summary>
    /// 系统邮件
    /// </summary>
    [pbr::OriginalName("MAIL_TYPE_SYSTEM")] MailTypeSystem = 4,
    /// <summary>
    /// 个人聊天频道
    /// </summary>
    [pbr::OriginalName("CHAT_CHANNEL_PLAYER")] ChatChannelPlayer = 10,
    /// <summary>
    /// 世界聊天频道
    /// </summary>
    [pbr::OriginalName("CHAT_CHANNEL_WORLD")] ChatChannelWorld = 11,
    /// <summary>
    /// 联盟聊天频道
    /// </summary>
    [pbr::OriginalName("CHAT_CHANNEL_UNION")] ChatChannelUnion = 12,
  }

  /// <summary>
  /// 刷新方式
  /// </summary>
  public enum REFRESH_TYPE {
    /// <summary>
    /// 未使用
    /// </summary>
    [pbr::OriginalName("REFRESH_NONE")] RefreshNone = 0,
    /// <summary>
    /// 全部刷新
    /// </summary>
    [pbr::OriginalName("REFRESH_ALL")] RefreshAll = 1,
    /// <summary>
    /// 增量刷新
    /// </summary>
    [pbr::OriginalName("REFRESH_INC")] RefreshInc = 2,
  }

  /// <summary>
  /// 聊天消息状态
  /// </summary>
  public enum CHAT_STATUS {
    [pbr::OriginalName("UNREAD")] Unread = 0,
    [pbr::OriginalName("READ")] Read = 1,
  }

  /// <summary>
  /// 登录类型
  /// </summary>
  public enum LOGIN_ACTION {
    [pbr::OriginalName("LOGIN")] Login = 0,
    [pbr::OriginalName("REGISTER")] Register = 1,
  }

  /// <summary>
  /// 联盟成员职位（包含非成员）
  /// </summary>
  public enum UNION_TITLE_TYPE {
    /// <summary>
    /// 非盟众
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_NOT_MEMBER")] UnionTitleNotMember = 0,
    /// <summary>
    /// 盟主
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_LEADER")] UnionTitleLeader = 1,
    /// <summary>
    /// 副盟主
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_DEPUTY_LEADER")] UnionTitleDeputyLeader = 2,
    /// <summary>
    /// 指挥官
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_COMMANDER_A")] UnionTitleCommanderA = 3,
    /// <summary>
    /// 官员
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_COMMANDER_B")] UnionTitleCommanderB = 4,
    /// <summary>
    /// 盟众
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_MEMBER")] UnionTitleMember = 5,
    /// <summary>
    /// 禁言
    /// </summary>
    [pbr::OriginalName("UNION_TITLE_BANNED")] UnionTitleBanned = 6,
  }

  /// <summary>
  /// 联盟操作ID（权限相关）
  /// </summary>
  public enum UNION_OP_TYPE {
    [pbr::OriginalName("UNION_OP_DO_NOTHING")] UnionOpDoNothing = 0,
    /// <summary>
    /// 创建联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_CREATE_UNION")] UnionOpCreateUnion = 1,
    /// <summary>
    /// 查看联盟列表信息
    /// </summary>
    [pbr::OriginalName("UNION_OP_GET_UNION_INFO_LIST")] UnionOpGetUnionInfoList = 2,
    /// <summary>
    /// 申请加入联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_APPLY_UNION")] UnionOpApplyUnion = 3,
    /// <summary>
    /// 取消申请加入联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_CANCEL_APPLY_UNION")] UnionOpCancelApplyUnion = 4,
    /// <summary>
    /// 直接加入联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_JOIN_UNION")] UnionOpJoinUnion = 5,
    /// <summary>
    /// 解散联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_DISSOLVE_UNION")] UnionOpDissolveUnion = 101,
    /// <summary>
    /// 禅让盟主
    /// </summary>
    [pbr::OriginalName("UNION_OP_DEMISE")] UnionOpDemise = 102,
    /// <summary>
    /// 设置同盟外交关系
    /// </summary>
    [pbr::OriginalName("UNION_OP_SET_RELATION")] UnionOpSetRelation = 103,
    /// <summary>
    /// 审批是否同意申请加入
    /// </summary>
    [pbr::OriginalName("UNION_OP_APPROVE_APPLY")] UnionOpApproveApply = 105,
    /// <summary>
    /// 移除成员
    /// </summary>
    [pbr::OriginalName("UNION_OP_REMOVE_MEMBER")] UnionOpRemoveMember = 106,
    /// <summary>
    /// 设置加入联盟条件
    /// </summary>
    [pbr::OriginalName("UNION_OP_SET_JOIN_LIMIT")] UnionOpSetJoinLimit = 107,
    /// <summary>
    /// 设置联盟公告
    /// </summary>
    [pbr::OriginalName("UNION_OP_SET_UNION_DESC")] UnionOpSetUnionDesc = 108,
    /// <summary>
    /// 创建联盟标记
    /// </summary>
    [pbr::OriginalName("UNION_OP_ADD_MARK")] UnionOpAddMark = 110,
    /// <summary>
    /// 任命成员
    /// </summary>
    [pbr::OriginalName("UNION_OP_APPOINT_MEMBER")] UnionOpAppointMember = 111,
    /// <summary>
    /// 放弃职位
    /// </summary>
    [pbr::OriginalName("UNION_OP_GIVEUP_TITLE")] UnionOpGiveupTitle = 114,
    /// <summary>
    /// 查看联盟信息
    /// </summary>
    [pbr::OriginalName("UNION_OP_GET_UNION_INFO")] UnionOpGetUnionInfo = 116,
    /// <summary>
    /// 退出联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_QUIT_UNION")] UnionOpQuitUnion = 122,
    /// <summary>
    /// 邀请加入联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_INVITE_JOIN_UNION")] UnionOpInviteJoinUnion = 123,
    /// <summary>
    /// 处理联盟邀请
    /// </summary>
    [pbr::OriginalName("UNION_OP_DEAL_INVITE")] UnionOpDealInvite = 124,
    /// <summary>
    /// 查找联盟
    /// </summary>
    [pbr::OriginalName("UNION_OP_FIND_UNION")] UnionOpFindUnion = 125,
    /// <summary>
    /// 联盟捐赠
    /// </summary>
    [pbr::OriginalName("UNION_OP_DONATE")] UnionOpDonate = 126,
    /// <summary>
    /// 删除联盟标记
    /// </summary>
    [pbr::OriginalName("UNION_OP_DEL_MARK")] UnionOpDelMark = 127,
    /// <summary>
    /// 替换职位
    /// </summary>
    [pbr::OriginalName("UNION_OP_SWAP_TITLE")] UnionOpSwapTitle = 128,
    /// <summary>
    /// 取消禅让
    /// </summary>
    [pbr::OriginalName("UNION_OP_CANCEL_DEMISE")] UnionOpCancelDemise = 129,
    /// <summary>
    /// 发送联盟邮件
    /// </summary>
    [pbr::OriginalName("UNION_OP_SEND_UNION_MAIL")] UnionOpSendUnionMail = 130,
  }

  /// <summary>
  /// 联盟加入条件
  /// </summary>
  public enum UNION_JOIN_LIMIT {
    /// <summary>
    /// 没有条件，直接加入
    /// </summary>
    [pbr::OriginalName("UNION_JOIN_NO_LIMIT")] UnionJoinNoLimit = 0,
    /// <summary>
    /// 需要申请加入
    /// </summary>
    [pbr::OriginalName("UNION_JOIN_NEED_APPLY")] UnionJoinNeedApply = 1,
    /// <summary>
    /// 无需申请，满足条件直接加入（暂未实现）
    /// </summary>
    [pbr::OriginalName("UNION_JOIN_NO_APPLY_WITH_LIMIT")] UnionJoinNoApplyWithLimit = 2,
    /// <summary>
    /// 禁止加入
    /// </summary>
    [pbr::OriginalName("UNION_JOIN_FORBID")] UnionJoinForbid = 3,
  }

  /// <summary>
  /// 联盟关系
  /// </summary>
  public enum UNION_RELATION_TYPE {
    /// <summary>
    /// 无关系
    /// </summary>
    [pbr::OriginalName("UNION_RELATION_NONE")] UnionRelationNone = 0,
    /// <summary>
    /// 友好关系
    /// </summary>
    [pbr::OriginalName("UNION_RELATION_FRIENDLY")] UnionRelationFriendly = 1,
    /// <summary>
    /// 敌对关系
    /// </summary>
    [pbr::OriginalName("UNION_RELATION_HOSTILE")] UnionRelationHostile = 2,
  }

  /// <summary>
  /// 联盟日志类型
  /// </summary>
  public enum UNION_LOG_TYPE {
    /// <summary>
    /// 联盟事件
    /// </summary>
    [pbr::OriginalName("UNION_LOG_EVENT")] UnionLogEvent = 0,
    /// <summary>
    /// 联盟成员
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER")] UnionLogMember = 1,
    /// <summary>
    /// 联盟战斗
    /// </summary>
    [pbr::OriginalName("UNION_LOG_FIGHT")] UnionLogFight = 2,
    /// <summary>
    /// 联盟关系
    /// </summary>
    [pbr::OriginalName("UNION_LOG_RELATION")] UnionLogRelation = 3,
  }

  /// <summary>
  /// 联盟事件日志类型
  /// </summary>
  public enum UNION_LOG_EVENT_TYPE {
    /// <summary>
    /// 联盟%s成功建立
    /// </summary>
    [pbr::OriginalName("UNION_LOG_EVENT_SETUP")] UnionLogEventSetup = 0,
    /// <summary>
    /// 联盟等级上升至%s
    /// </summary>
    [pbr::OriginalName("UNION_LOG_EVENT_LEVELUP")] UnionLogEventLevelup = 1,
    /// <summary>
    /// %s关闭了联盟申请
    /// </summary>
    [pbr::OriginalName("UNION_LOG_EVENT_CLOSE_APPLY")] UnionLogEventCloseApply = 2,
  }

  /// <summary>
  /// 联盟成员日志类型
  /// </summary>
  public enum UNION_LOG_MEMBER_TYPE {
    /// <summary>
    /// %s加入了联盟%s
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_JOIN")] UnionLogMemberJoin = 0,
    /// <summary>
    /// %s将%s任命为%s
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_APPOINT")] UnionLogMemberAppoint = 1,
    /// <summary>
    /// %s罢免了%s的%s官位
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_DISMISS")] UnionLogMemberDismiss = 2,
    /// <summary>
    /// %s离开了%s
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_QUIT")] UnionLogMemberQuit = 3,
    /// <summary>
    /// %s被%s移出了联盟
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_REMOVE")] UnionLogMemberRemove = 4,
    /// <summary>
    /// %s被攻击失去分城
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_ATTACKED_LOST_CITY")] UnionLogMemberAttackedLostCity = 5,
    /// <summary>
    /// %s的主城被攻击
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_ATTACKED_MCITY")] UnionLogMemberAttackedMcity = 6,
    /// <summary>
    /// %s被联盟%s的%s攻击沦陷
    /// </summary>
    [pbr::OriginalName("UNION_LOG_MEMBER_ATTACKED_FALLEN")] UnionLogMemberAttackedFallen = 7,
  }

  /// <summary>
  /// 联盟战斗日志类型
  /// </summary>
  public enum UNION_LOG_FIGHT_TYPE {
    /// <summary>
    /// %s对友好联盟%s的%s进行了攻击
    /// </summary>
    [pbr::OriginalName("UNION_LOG_FIGHT_ATTACK")] UnionLogFightAttack = 0,
    /// <summary>
    /// 联盟失去了城池%s
    /// </summary>
    [pbr::OriginalName("UNION_LOG_FIGHT_LOST_CITY")] UnionLogFightLostCity = 1,
  }

  /// <summary>
  /// 联盟关系日志类型
  /// </summary>
  public enum UNION_LOG_RELATION_TYPE {
    /// <summary>
    /// %s将联盟%s设置为%s关系
    /// </summary>
    [pbr::OriginalName("UNION_LOG_RELATION_SETUP")] UnionLogRelationSetup = 0,
  }

  /// <summary>
  /// 联盟距离
  /// </summary>
  public enum UNION_DISTANCE_TYPE {
    /// <summary>
    /// 近，[0, 40)
    /// </summary>
    [pbr::OriginalName("UNION_DISTANCE_NEAR")] UnionDistanceNear = 0,
    /// <summary>
    /// 中，[40,80)
    /// </summary>
    [pbr::OriginalName("UNION_DISTANCE_MID")] UnionDistanceMid = 1,
    /// <summary>
    /// 远，[80, -)
    /// </summary>
    [pbr::OriginalName("UNION_DISTANCE_FAR")] UnionDistanceFar = 2,
  }

  /// <summary>
  /// 战役类型
  /// </summary>
  public enum CONFLICT_TYPE {
    [pbr::OriginalName("CONFLICT_TYPE_PVP")] Pvp = 0,
    [pbr::OriginalName("CONFLICT_TYPE_PVE")] Pve = 1,
  }

  public enum BATTLE_RESULT {
    /// <summary>
    /// 攻方胜
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_ATKWIN")] Atkwin = 0,
    /// <summary>
    /// 守方胜
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_DEFWIN")] Defwin = 1,
    /// <summary>
    /// 平局
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_DRAW")] Draw = 2,
    /// <summary>
    /// 两败俱伤
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_BOTH_DEAD")] BothDead = 3,
    /// <summary>
    /// 未战（无原因）
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_NO_FIGHT")] NoFight = 4,
    /// <summary>
    /// 未战 免战期间
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_PROTECT")] Protect = 5,
    /// <summary>
    /// 未战 没有连接地
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_NO_NEARBY")] NoNearby = 6,
    /// <summary>
    /// 未战 坚守中
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_GUARD")] Guard = 7,
    /// <summary>
    /// 战斗脚本异常
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_EXCEPTION")] Exception = 9,
    /// <summary>
    /// 战胜，土地达到上限，不能占领
    /// </summary>
    [pbr::OriginalName("BATTLE_RESULT_TILE_FULL")] TileFull = 10,
  }

  public enum BATTLE_AWARD_TYPE {
    /// <summary>
    ///补给
    /// </summary>
    [pbr::OriginalName("BATTLE_AWARD_SUPPLY")] BattleAwardSupply = 0,
  }

  public enum OWNER_TYPE {
    [pbr::OriginalName("OCCUPY_OWNER_TYPE_PLAYER")] OccupyOwnerTypePlayer = 0,
    [pbr::OriginalName("OCCUPY_OWNER_TYPE_UNION")] OccupyOwnerTypeUnion = 1,
  }

  public enum DRILL_ID_DEF {
    /// <summary>
    /// 没有选择关卡
    /// </summary>
    [pbr::OriginalName("DRILL_NO_SELECT")] DrillNoSelect = 0,
    /// <summary>
    /// 教学关最小关卡ID
    /// </summary>
    [pbr::OriginalName("DRILL_TUTORIAL_MIN")] DrillTutorialMin = 1,
    /// <summary>
    /// 教学关最大关卡ID
    /// </summary>
    [pbr::OriginalName("DRILL_TUTORIAL_MAX")] DrillTutorialMax = 1000,
    /// <summary>
    /// 日常关最小关卡ID
    /// </summary>
    [pbr::OriginalName("DRILL_NORMAL_MIN")] DrillNormalMin = 1001,
    /// <summary>
    /// 日常关最大关卡ID
    /// </summary>
    [pbr::OriginalName("DRILL_NORMAL_MAX")] DrillNormalMax = 2000,
  }

  /// <summary>
  /// "tutorial_level"表中"request"列值定义
  /// </summary>
  public enum DRILL_CONDITION_TYPE {
    /// <summary>
    /// 没有前置条件
    /// </summary>
    [pbr::OriginalName("DRILL_CONDITION_NO")] DrillConditionNo = 0,
    /// <summary>
    /// 任务类前置条件
    /// </summary>
    [pbr::OriginalName("DRILL_CONDITION_MISSION")] DrillConditionMission = 1,
    /// <summary>
    /// 天下大势类前置条件
    /// </summary>
    [pbr::OriginalName("DRILL_CONDITION_WORLD")] DrillConditionWorld = 2,
  }

  /// <summary>
  /// "tutorial_maptile"表中"positionAttribute"列的值定义
  /// </summary>
  public enum DRILL_TILE_ATTRIBUTE {
    /// <summary>
    /// 普通土地
    /// </summary>
    [pbr::OriginalName("DRILL_TILE_NORMAL")] DrillTileNormal = 0,
    /// <summary>
    /// 关卡起始土地
    /// </summary>
    [pbr::OriginalName("DRILL_TILE_START")] DrillTileStart = 1,
    /// <summary>
    /// 关卡终止土地
    /// </summary>
    [pbr::OriginalName("DRILL_TILE_END")] DrillTileEnd = 2,
    /// <summary>
    /// 大于等于该值时，表示该土地耐久值
    /// </summary>
    [pbr::OriginalName("DRILL_TILE_DURABLE")] DrillTileDurable = 100,
  }

  public enum EPIC_STATE {
    [pbr::OriginalName("EPIC_STATES_INIT")] SInit = 0,
    [pbr::OriginalName("EPIC_STATES_START")] SStart = 1,
    [pbr::OriginalName("EPIC_STATES_COMPLETE")] SComplete = 2,
    [pbr::OriginalName("EPIC_STATES_AWARD")] SAward = 3,
  }

  public enum EPIC_PLAYER_STATE {
    [pbr::OriginalName("EPIC_PLAYER_STATES_NONE")] SNone = 0,
    [pbr::OriginalName("EPIC_PLAYER_STATES_EXPIRE")] SExpire = 1,
    [pbr::OriginalName("EPIC_PLAYER_STATES_AWARDED")] SAwarded = 2,
  }

  /// <summary>
  /// 服务器开放状态
  /// </summary>
  public enum SRV_STATUS {
    /// <summary>
    /// 开放
    /// </summary>
    [pbr::OriginalName("SRV_STATUS_OPEN")] Open = 0,
    /// <summary>
    /// 维护
    /// </summary>
    [pbr::OriginalName("SRV_STATUS_CLOSE")] Close = 1,
  }

  /// <summary>
  /// 兵种类型
  /// </summary>
  public enum HERO_ARM_TYPE {
    /// <summary>
    /// 未知兵种
    /// </summary>
    [pbr::OriginalName("HERO_ARM_NONE")] HeroArmNone = 0,
    /// <summary>
    /// 步兵系
    /// </summary>
    [pbr::OriginalName("HERO_ARM_INFANTRY")] HeroArmInfantry = 10,
    /// <summary>
    /// 重步兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_HEAVY_INFANTRY")] HeroArmHeavyInfantry = 11,
    /// <summary>
    /// 近卫
    /// </summary>
    [pbr::OriginalName("HERO_ARM_GUARD_INFANTRY")] HeroArmGuardInfantry = 12,
    /// <summary>
    /// 长枪兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_SPEAR_INFANTRY")] HeroArmSpearInfantry = 13,
    /// <summary>
    /// 蛮兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_SAVAGE_INFANTRY")] HeroArmSavageInfantry = 14,
    /// <summary>
    /// 藤甲兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_RATTAN_INFANTRY")] HeroArmRattanInfantry = 15,
    /// <summary>
    /// 骑兵系
    /// </summary>
    [pbr::OriginalName("HERO_ARM_CAVALRY")] HeroArmCavalry = 20,
    /// <summary>
    /// 轻骑兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_LIGHT_CAVALRY")] HeroArmLightCavalry = 21,
    /// <summary>
    /// 重骑兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_HEAVY_CAVALRY")] HeroArmHeavyCavalry = 22,
    /// <summary>
    /// 铁骑兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_IRON_CAVALRY")] HeroArmIronCavalry = 23,
    /// <summary>
    /// 弓骑兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_BOW_CAVALRY")] HeroArmBowCavalry = 24,
    /// <summary>
    /// 象兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_ELEPHANT_CAVALRY")] HeroArmElephantCavalry = 25,
    /// <summary>
    /// 弓兵系
    /// </summary>
    [pbr::OriginalName("HERO_ARM_BOWMEN")] HeroArmBowmen = 30,
    /// <summary>
    /// 死士
    /// </summary>
    [pbr::OriginalName("HERO_ARM_DEAD_BOWMEN")] HeroArmDeadBowmen = 31,
    /// <summary>
    /// 长弓兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_LONG_BOWMEN")] HeroArmLongBowmen = 32,
    /// <summary>
    /// 弩兵
    /// </summary>
    [pbr::OriginalName("HERO_ARM_CROSS_BOWMEN")] HeroArmCrossBowmen = 33,
  }

  #endregion

}

#endregion Designer generated code
